// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: acl.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createBotACLRule = `-- name: CreateBotACLRule :one
INSERT INTO bot_acl_rules (
  id, bot_id, enabled, description,
  action, effect,
  channel_identity_id, subject_channel_type,
  source_channel, source_conversation_type,
  source_conversation_id, source_thread_id,
  created_by_user_id
)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  'chat.trigger',
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11
)
RETURNING id, bot_id, enabled, description, action, effect, channel_identity_id,
  subject_channel_type, source_channel, source_conversation_type, source_conversation_id, source_thread_id,
  created_by_user_id, created_at, updated_at
`

type CreateBotACLRuleParams struct {
	BotID                  string         `json:"bot_id"`
	Enabled                int64          `json:"enabled"`
	Description            sql.NullString `json:"description"`
	Effect                 string         `json:"effect"`
	ChannelIdentityID      sql.NullString `json:"channel_identity_id"`
	SubjectChannelType     sql.NullString `json:"subject_channel_type"`
	SourceChannel          sql.NullString `json:"source_channel"`
	SourceConversationType sql.NullString `json:"source_conversation_type"`
	SourceConversationID   sql.NullString `json:"source_conversation_id"`
	SourceThreadID         sql.NullString `json:"source_thread_id"`
	CreatedByUserID        sql.NullString `json:"created_by_user_id"`
}

func (q *Queries) CreateBotACLRule(ctx context.Context, arg CreateBotACLRuleParams) (BotAclRule, error) {
	row := q.db.QueryRowContext(ctx, createBotACLRule,
		arg.BotID,
		arg.Enabled,
		arg.Description,
		arg.Effect,
		arg.ChannelIdentityID,
		arg.SubjectChannelType,
		arg.SourceChannel,
		arg.SourceConversationType,
		arg.SourceConversationID,
		arg.SourceThreadID,
		arg.CreatedByUserID,
	)
	var i BotAclRule
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Enabled,
		&i.Description,
		&i.Action,
		&i.Effect,
		&i.ChannelIdentityID,
		&i.SubjectChannelType,
		&i.SourceChannel,
		&i.SourceConversationType,
		&i.SourceConversationID,
		&i.SourceThreadID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBotACLRuleByID = `-- name: DeleteBotACLRuleByID :exec
DELETE FROM bot_acl_rules WHERE id = ?1
`

func (q *Queries) DeleteBotACLRuleByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBotACLRuleByID, id)
	return err
}

const evaluateBotACLRule = `-- name: EvaluateBotACLRule :one
SELECT COALESCE((
  SELECT r.effect
  FROM bot_acl_rules r
  WHERE r.bot_id = b.id
    AND r.enabled = true
    AND r.action = ?1
    AND r.effect <> b.acl_default_effect
    AND (r.subject_channel_type IS NULL OR r.subject_channel_type = ?2)
    AND (r.channel_identity_id IS NULL OR r.channel_identity_id = ?3)
    AND (r.source_conversation_type IS NULL OR r.source_conversation_type = ?4)
    AND (r.source_conversation_id IS NULL OR r.source_conversation_id = ?5)
    AND (r.source_thread_id IS NULL OR r.source_thread_id = ?6)
  LIMIT 1
), b.acl_default_effect) AS effect
FROM bots b
WHERE b.id = ?7
`

type EvaluateBotACLRuleParams struct {
	Action                 string         `json:"action"`
	SubjectChannelType     sql.NullString `json:"subject_channel_type"`
	ChannelIdentityID      sql.NullString `json:"channel_identity_id"`
	SourceConversationType sql.NullString `json:"source_conversation_type"`
	SourceConversationID   sql.NullString `json:"source_conversation_id"`
	SourceThreadID         sql.NullString `json:"source_thread_id"`
	BotID                  string         `json:"bot_id"`
}

// Mode-based ACL: only rules opposite to bots.acl_default_effect can override the default.
// If no matching override exists, returns bots.acl_default_effect.
func (q *Queries) EvaluateBotACLRule(ctx context.Context, arg EvaluateBotACLRuleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, evaluateBotACLRule,
		arg.Action,
		arg.SubjectChannelType,
		arg.ChannelIdentityID,
		arg.SourceConversationType,
		arg.SourceConversationID,
		arg.SourceThreadID,
		arg.BotID,
	)
	var effect string
	err := row.Scan(&effect)
	return effect, err
}

const getBotACLDefaultEffect = `-- name: GetBotACLDefaultEffect :one
SELECT acl_default_effect FROM bots WHERE id = ?1
`

func (q *Queries) GetBotACLDefaultEffect(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getBotACLDefaultEffect, id)
	var acl_default_effect string
	err := row.Scan(&acl_default_effect)
	return acl_default_effect, err
}

const listBotACLRules = `-- name: ListBotACLRules :many
SELECT
  r.id,
  r.bot_id,
  r.enabled,
  r.description,
  r.action,
  r.effect,
  r.channel_identity_id,
  r.subject_channel_type,
  r.source_conversation_type,
  r.source_conversation_id,
  r.source_thread_id,
  r.created_by_user_id,
  r.created_at,
  r.updated_at,
  ci.channel_type,
  ci.channel_subject_id,
  ci.display_name AS channel_identity_display_name,
  ci.avatar_url AS channel_identity_avatar_url,
  COALESCE(
    NULLIF(TRIM(COALESCE(json_extract(source_route.metadata, '$.conversation_name'), '')), ''),
    NULLIF(TRIM(COALESCE(json_extract(source_route.metadata, '$.conversation_handle'), '')), ''),
    ''
  ) AS source_conversation_name,
  COALESCE(NULLIF(TRIM(COALESCE(json_extract(source_route.metadata, '$.conversation_avatar_url'), '')), ''), '') AS source_conversation_avatar_url
FROM bot_acl_rules r
LEFT JOIN channel_identities ci ON ci.id = r.channel_identity_id
LEFT JOIN bot_channel_routes source_route ON source_route.bot_id = r.bot_id
  AND r.source_conversation_id IS NOT NULL
  AND source_route.external_conversation_id = r.source_conversation_id
  AND COALESCE(source_route.external_thread_id, '') = COALESCE(r.source_thread_id, '')
  AND (r.source_channel IS NULL OR source_route.channel_type = r.source_channel)
WHERE r.bot_id = ?1
  AND r.action = 'chat.trigger'
ORDER BY r.created_at DESC
`

type ListBotACLRulesRow struct {
	ID                          string         `json:"id"`
	BotID                       string         `json:"bot_id"`
	Enabled                     int64          `json:"enabled"`
	Description                 sql.NullString `json:"description"`
	Action                      string         `json:"action"`
	Effect                      string         `json:"effect"`
	ChannelIdentityID           sql.NullString `json:"channel_identity_id"`
	SubjectChannelType          sql.NullString `json:"subject_channel_type"`
	SourceConversationType      sql.NullString `json:"source_conversation_type"`
	SourceConversationID        sql.NullString `json:"source_conversation_id"`
	SourceThreadID              sql.NullString `json:"source_thread_id"`
	CreatedByUserID             sql.NullString `json:"created_by_user_id"`
	CreatedAt                   string         `json:"created_at"`
	UpdatedAt                   string         `json:"updated_at"`
	ChannelType                 sql.NullString `json:"channel_type"`
	ChannelSubjectID            sql.NullString `json:"channel_subject_id"`
	ChannelIdentityDisplayName  sql.NullString `json:"channel_identity_display_name"`
	ChannelIdentityAvatarUrl    sql.NullString `json:"channel_identity_avatar_url"`
	SourceConversationName      interface{}    `json:"source_conversation_name"`
	SourceConversationAvatarUrl interface{}    `json:"source_conversation_avatar_url"`
}

func (q *Queries) ListBotACLRules(ctx context.Context, botID string) ([]ListBotACLRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listBotACLRules, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBotACLRulesRow
	for rows.Next() {
		var i ListBotACLRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Enabled,
			&i.Description,
			&i.Action,
			&i.Effect,
			&i.ChannelIdentityID,
			&i.SubjectChannelType,
			&i.SourceConversationType,
			&i.SourceConversationID,
			&i.SourceThreadID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelType,
			&i.ChannelSubjectID,
			&i.ChannelIdentityDisplayName,
			&i.ChannelIdentityAvatarUrl,
			&i.SourceConversationName,
			&i.SourceConversationAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBotACLDefaultEffect = `-- name: SetBotACLDefaultEffect :exec
UPDATE bots SET acl_default_effect = ?1, updated_at = CURRENT_TIMESTAMP WHERE id = ?2
`

type SetBotACLDefaultEffectParams struct {
	AclDefaultEffect string `json:"acl_default_effect"`
	ID               string `json:"id"`
}

func (q *Queries) SetBotACLDefaultEffect(ctx context.Context, arg SetBotACLDefaultEffectParams) error {
	_, err := q.db.ExecContext(ctx, setBotACLDefaultEffect, arg.AclDefaultEffect, arg.ID)
	return err
}

const updateBotACLRule = `-- name: UpdateBotACLRule :one
UPDATE bot_acl_rules
SET
  enabled = ?1,
  description = ?2,
  effect = ?3,
  channel_identity_id = ?4,
  subject_channel_type = ?5,
  source_channel = ?6,
  source_conversation_type = ?7,
  source_conversation_id = ?8,
  source_thread_id = ?9,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?10
RETURNING id, bot_id, enabled, description, action, effect, channel_identity_id,
  subject_channel_type, source_channel, source_conversation_type, source_conversation_id, source_thread_id,
  created_by_user_id, created_at, updated_at
`

type UpdateBotACLRuleParams struct {
	Enabled                int64          `json:"enabled"`
	Description            sql.NullString `json:"description"`
	Effect                 string         `json:"effect"`
	ChannelIdentityID      sql.NullString `json:"channel_identity_id"`
	SubjectChannelType     sql.NullString `json:"subject_channel_type"`
	SourceChannel          sql.NullString `json:"source_channel"`
	SourceConversationType sql.NullString `json:"source_conversation_type"`
	SourceConversationID   sql.NullString `json:"source_conversation_id"`
	SourceThreadID         sql.NullString `json:"source_thread_id"`
	ID                     string         `json:"id"`
}

func (q *Queries) UpdateBotACLRule(ctx context.Context, arg UpdateBotACLRuleParams) (BotAclRule, error) {
	row := q.db.QueryRowContext(ctx, updateBotACLRule,
		arg.Enabled,
		arg.Description,
		arg.Effect,
		arg.ChannelIdentityID,
		arg.SubjectChannelType,
		arg.SourceChannel,
		arg.SourceConversationType,
		arg.SourceConversationID,
		arg.SourceThreadID,
		arg.ID,
	)
	var i BotAclRule
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Enabled,
		&i.Description,
		&i.Action,
		&i.Effect,
		&i.ChannelIdentityID,
		&i.SubjectChannelType,
		&i.SourceChannel,
		&i.SourceConversationType,
		&i.SourceConversationID,
		&i.SourceThreadID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
