// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bots.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createBot = `-- name: CreateBot :one
INSERT INTO bots (id, owner_user_id, type, name, display_name, avatar_url, timezone, is_active, metadata, status)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  'personal',
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
)
RETURNING id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
`

type CreateBotParams struct {
	OwnerUserID string         `json:"owner_user_id"`
	Name        string         `json:"name"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Timezone    sql.NullString `json:"timezone"`
	IsActive    int64          `json:"is_active"`
	Metadata    string         `json:"metadata"`
	Status      string         `json:"status"`
}

type CreateBotRow struct {
	ID                string         `json:"id"`
	OwnerUserID       string         `json:"owner_user_id"`
	Name              string         `json:"name"`
	DisplayName       sql.NullString `json:"display_name"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	Timezone          sql.NullString `json:"timezone"`
	IsActive          int64          `json:"is_active"`
	Status            string         `json:"status"`
	Language          string         `json:"language"`
	ReasoningEnabled  int64          `json:"reasoning_enabled"`
	ReasoningEffort   string         `json:"reasoning_effort"`
	ChatModelID       sql.NullString `json:"chat_model_id"`
	SearchProviderID  sql.NullString `json:"search_provider_id"`
	MemoryProviderID  sql.NullString `json:"memory_provider_id"`
	HeartbeatEnabled  int64          `json:"heartbeat_enabled"`
	HeartbeatInterval int64          `json:"heartbeat_interval"`
	HeartbeatPrompt   string         `json:"heartbeat_prompt"`
	Metadata          string         `json:"metadata"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (CreateBotRow, error) {
	row := q.db.QueryRowContext(ctx, createBot,
		arg.OwnerUserID,
		arg.Name,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Timezone,
		arg.IsActive,
		arg.Metadata,
		arg.Status,
	)
	var i CreateBotRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBotByID = `-- name: DeleteBotByID :exec
DELETE FROM bots WHERE id = ?1
`

func (q *Queries) DeleteBotByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBotByID, id)
	return err
}

const getBotByID = `-- name: GetBotByID :one
SELECT id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, compaction_enabled, compaction_threshold, compaction_ratio, compaction_model_id, metadata, created_at, updated_at
FROM bots
WHERE id = ?1
`

type GetBotByIDRow struct {
	ID                  string         `json:"id"`
	OwnerUserID         string         `json:"owner_user_id"`
	Name                string         `json:"name"`
	DisplayName         sql.NullString `json:"display_name"`
	AvatarUrl           sql.NullString `json:"avatar_url"`
	Timezone            sql.NullString `json:"timezone"`
	IsActive            int64          `json:"is_active"`
	Status              string         `json:"status"`
	Language            string         `json:"language"`
	ReasoningEnabled    int64          `json:"reasoning_enabled"`
	ReasoningEffort     string         `json:"reasoning_effort"`
	ChatModelID         sql.NullString `json:"chat_model_id"`
	SearchProviderID    sql.NullString `json:"search_provider_id"`
	MemoryProviderID    sql.NullString `json:"memory_provider_id"`
	HeartbeatEnabled    int64          `json:"heartbeat_enabled"`
	HeartbeatInterval   int64          `json:"heartbeat_interval"`
	HeartbeatPrompt     string         `json:"heartbeat_prompt"`
	CompactionEnabled   int64          `json:"compaction_enabled"`
	CompactionThreshold int64          `json:"compaction_threshold"`
	CompactionRatio     int64          `json:"compaction_ratio"`
	CompactionModelID   sql.NullString `json:"compaction_model_id"`
	Metadata            string         `json:"metadata"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
}

func (q *Queries) GetBotByID(ctx context.Context, id string) (GetBotByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBotByID, id)
	var i GetBotByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionRatio,
		&i.CompactionModelID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotByName = `-- name: GetBotByName :one
SELECT id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, compaction_enabled, compaction_threshold, compaction_ratio, compaction_model_id, metadata, created_at, updated_at
FROM bots
WHERE name = ?1
`

type GetBotByNameRow struct {
	ID                  string         `json:"id"`
	OwnerUserID         string         `json:"owner_user_id"`
	Name                string         `json:"name"`
	DisplayName         sql.NullString `json:"display_name"`
	AvatarUrl           sql.NullString `json:"avatar_url"`
	Timezone            sql.NullString `json:"timezone"`
	IsActive            int64          `json:"is_active"`
	Status              string         `json:"status"`
	Language            string         `json:"language"`
	ReasoningEnabled    int64          `json:"reasoning_enabled"`
	ReasoningEffort     string         `json:"reasoning_effort"`
	ChatModelID         sql.NullString `json:"chat_model_id"`
	SearchProviderID    sql.NullString `json:"search_provider_id"`
	MemoryProviderID    sql.NullString `json:"memory_provider_id"`
	HeartbeatEnabled    int64          `json:"heartbeat_enabled"`
	HeartbeatInterval   int64          `json:"heartbeat_interval"`
	HeartbeatPrompt     string         `json:"heartbeat_prompt"`
	CompactionEnabled   int64          `json:"compaction_enabled"`
	CompactionThreshold int64          `json:"compaction_threshold"`
	CompactionRatio     int64          `json:"compaction_ratio"`
	CompactionModelID   sql.NullString `json:"compaction_model_id"`
	Metadata            string         `json:"metadata"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
}

func (q *Queries) GetBotByName(ctx context.Context, name string) (GetBotByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getBotByName, name)
	var i GetBotByNameRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionRatio,
		&i.CompactionModelID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccessibleBots = `-- name: ListAccessibleBots :many
SELECT id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
FROM bots b
WHERE b.owner_user_id = ?1
   OR EXISTS (
     SELECT 1 FROM bot_user_grants g
     WHERE g.bot_id = b.id
       AND (
         g.subject_type = 'everyone'
         OR (g.subject_type = 'user' AND g.user_id = ?1)
       )
   )
ORDER BY b.created_at DESC
`

type ListAccessibleBotsRow struct {
	ID                string         `json:"id"`
	OwnerUserID       string         `json:"owner_user_id"`
	Name              string         `json:"name"`
	DisplayName       sql.NullString `json:"display_name"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	Timezone          sql.NullString `json:"timezone"`
	IsActive          int64          `json:"is_active"`
	Status            string         `json:"status"`
	Language          string         `json:"language"`
	ReasoningEnabled  int64          `json:"reasoning_enabled"`
	ReasoningEffort   string         `json:"reasoning_effort"`
	ChatModelID       sql.NullString `json:"chat_model_id"`
	SearchProviderID  sql.NullString `json:"search_provider_id"`
	MemoryProviderID  sql.NullString `json:"memory_provider_id"`
	HeartbeatEnabled  int64          `json:"heartbeat_enabled"`
	HeartbeatInterval int64          `json:"heartbeat_interval"`
	HeartbeatPrompt   string         `json:"heartbeat_prompt"`
	Metadata          string         `json:"metadata"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

func (q *Queries) ListAccessibleBots(ctx context.Context, userID string) ([]ListAccessibleBotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAccessibleBots, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessibleBotsRow
	for rows.Next() {
		var i ListAccessibleBotsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Timezone,
			&i.IsActive,
			&i.Status,
			&i.Language,
			&i.ReasoningEnabled,
			&i.ReasoningEffort,
			&i.ChatModelID,
			&i.SearchProviderID,
			&i.MemoryProviderID,
			&i.HeartbeatEnabled,
			&i.HeartbeatInterval,
			&i.HeartbeatPrompt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotsByOwner = `-- name: ListBotsByOwner :many
SELECT id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
FROM bots
WHERE owner_user_id = ?1
ORDER BY created_at DESC
`

type ListBotsByOwnerRow struct {
	ID                string         `json:"id"`
	OwnerUserID       string         `json:"owner_user_id"`
	Name              string         `json:"name"`
	DisplayName       sql.NullString `json:"display_name"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	Timezone          sql.NullString `json:"timezone"`
	IsActive          int64          `json:"is_active"`
	Status            string         `json:"status"`
	Language          string         `json:"language"`
	ReasoningEnabled  int64          `json:"reasoning_enabled"`
	ReasoningEffort   string         `json:"reasoning_effort"`
	ChatModelID       sql.NullString `json:"chat_model_id"`
	SearchProviderID  sql.NullString `json:"search_provider_id"`
	MemoryProviderID  sql.NullString `json:"memory_provider_id"`
	HeartbeatEnabled  int64          `json:"heartbeat_enabled"`
	HeartbeatInterval int64          `json:"heartbeat_interval"`
	HeartbeatPrompt   string         `json:"heartbeat_prompt"`
	Metadata          string         `json:"metadata"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

func (q *Queries) ListBotsByOwner(ctx context.Context, ownerUserID string) ([]ListBotsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listBotsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBotsByOwnerRow
	for rows.Next() {
		var i ListBotsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Timezone,
			&i.IsActive,
			&i.Status,
			&i.Language,
			&i.ReasoningEnabled,
			&i.ReasoningEffort,
			&i.ChatModelID,
			&i.SearchProviderID,
			&i.MemoryProviderID,
			&i.HeartbeatEnabled,
			&i.HeartbeatInterval,
			&i.HeartbeatPrompt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeartbeatEnabledBots = `-- name: ListHeartbeatEnabledBots :many
SELECT id, owner_user_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt
FROM bots
WHERE heartbeat_enabled = true AND status = 'ready'
`

type ListHeartbeatEnabledBotsRow struct {
	ID                string `json:"id"`
	OwnerUserID       string `json:"owner_user_id"`
	HeartbeatEnabled  int64  `json:"heartbeat_enabled"`
	HeartbeatInterval int64  `json:"heartbeat_interval"`
	HeartbeatPrompt   string `json:"heartbeat_prompt"`
}

func (q *Queries) ListHeartbeatEnabledBots(ctx context.Context) ([]ListHeartbeatEnabledBotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listHeartbeatEnabledBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHeartbeatEnabledBotsRow
	for rows.Next() {
		var i ListHeartbeatEnabledBotsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.HeartbeatEnabled,
			&i.HeartbeatInterval,
			&i.HeartbeatPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBotOwner = `-- name: UpdateBotOwner :one
UPDATE bots
SET owner_user_id = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
RETURNING id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
`

type UpdateBotOwnerParams struct {
	OwnerUserID string `json:"owner_user_id"`
	ID          string `json:"id"`
}

type UpdateBotOwnerRow struct {
	ID                string         `json:"id"`
	OwnerUserID       string         `json:"owner_user_id"`
	Name              string         `json:"name"`
	DisplayName       sql.NullString `json:"display_name"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	Timezone          sql.NullString `json:"timezone"`
	IsActive          int64          `json:"is_active"`
	Status            string         `json:"status"`
	Language          string         `json:"language"`
	ReasoningEnabled  int64          `json:"reasoning_enabled"`
	ReasoningEffort   string         `json:"reasoning_effort"`
	ChatModelID       sql.NullString `json:"chat_model_id"`
	SearchProviderID  sql.NullString `json:"search_provider_id"`
	MemoryProviderID  sql.NullString `json:"memory_provider_id"`
	HeartbeatEnabled  int64          `json:"heartbeat_enabled"`
	HeartbeatInterval int64          `json:"heartbeat_interval"`
	HeartbeatPrompt   string         `json:"heartbeat_prompt"`
	Metadata          string         `json:"metadata"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

func (q *Queries) UpdateBotOwner(ctx context.Context, arg UpdateBotOwnerParams) (UpdateBotOwnerRow, error) {
	row := q.db.QueryRowContext(ctx, updateBotOwner, arg.OwnerUserID, arg.ID)
	var i UpdateBotOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotProfile = `-- name: UpdateBotProfile :one
UPDATE bots
SET name = ?1,
    display_name = ?2,
    avatar_url = ?3,
    timezone = ?4,
    is_active = ?5,
    metadata = ?6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?7
RETURNING id, owner_user_id, name, display_name, avatar_url, timezone, is_active, status, language, reasoning_enabled, reasoning_effort, chat_model_id, search_provider_id, memory_provider_id, heartbeat_enabled, heartbeat_interval, heartbeat_prompt, metadata, created_at, updated_at
`

type UpdateBotProfileParams struct {
	Name        string         `json:"name"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Timezone    sql.NullString `json:"timezone"`
	IsActive    int64          `json:"is_active"`
	Metadata    string         `json:"metadata"`
	ID          string         `json:"id"`
}

type UpdateBotProfileRow struct {
	ID                string         `json:"id"`
	OwnerUserID       string         `json:"owner_user_id"`
	Name              string         `json:"name"`
	DisplayName       sql.NullString `json:"display_name"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	Timezone          sql.NullString `json:"timezone"`
	IsActive          int64          `json:"is_active"`
	Status            string         `json:"status"`
	Language          string         `json:"language"`
	ReasoningEnabled  int64          `json:"reasoning_enabled"`
	ReasoningEffort   string         `json:"reasoning_effort"`
	ChatModelID       sql.NullString `json:"chat_model_id"`
	SearchProviderID  sql.NullString `json:"search_provider_id"`
	MemoryProviderID  sql.NullString `json:"memory_provider_id"`
	HeartbeatEnabled  int64          `json:"heartbeat_enabled"`
	HeartbeatInterval int64          `json:"heartbeat_interval"`
	HeartbeatPrompt   string         `json:"heartbeat_prompt"`
	Metadata          string         `json:"metadata"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

func (q *Queries) UpdateBotProfile(ctx context.Context, arg UpdateBotProfileParams) (UpdateBotProfileRow, error) {
	row := q.db.QueryRowContext(ctx, updateBotProfile,
		arg.Name,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Timezone,
		arg.IsActive,
		arg.Metadata,
		arg.ID,
	)
	var i UpdateBotProfileRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.IsActive,
		&i.Status,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.ChatModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotStatus = `-- name: UpdateBotStatus :exec
UPDATE bots
SET status = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateBotStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateBotStatus(ctx context.Context, arg UpdateBotStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBotStatus, arg.Status, arg.ID)
	return err
}
