// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel_identity_bindings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createChannelLinkCode = `-- name: CreateChannelLinkCode :one
INSERT INTO channel_link_codes (token, user_id, channel_type, expires_at)
VALUES (?1, ?2, ?3, ?4)
RETURNING token, user_id, channel_type, expires_at, consumed_at, consumed_channel_identity_id, created_at
`

type CreateChannelLinkCodeParams struct {
	Token       string `json:"token"`
	UserID      string `json:"user_id"`
	ChannelType string `json:"channel_type"`
	ExpiresAt   string `json:"expires_at"`
}

func (q *Queries) CreateChannelLinkCode(ctx context.Context, arg CreateChannelLinkCodeParams) (ChannelLinkCode, error) {
	row := q.db.QueryRowContext(ctx, createChannelLinkCode,
		arg.Token,
		arg.UserID,
		arg.ChannelType,
		arg.ExpiresAt,
	)
	var i ChannelLinkCode
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ChannelType,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedChannelIdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserChannelIdentityBinding = `-- name: DeleteUserChannelIdentityBinding :exec
DELETE FROM user_channel_identity_bindings
WHERE user_id = ?1 AND channel_identity_id = ?2
`

type DeleteUserChannelIdentityBindingParams struct {
	UserID            string `json:"user_id"`
	ChannelIdentityID string `json:"channel_identity_id"`
}

func (q *Queries) DeleteUserChannelIdentityBinding(ctx context.Context, arg DeleteUserChannelIdentityBindingParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserChannelIdentityBinding, arg.UserID, arg.ChannelIdentityID)
	return err
}

const getChannelLinkCodeByToken = `-- name: GetChannelLinkCodeByToken :one
SELECT token, user_id, channel_type, expires_at, consumed_at, consumed_channel_identity_id, created_at
FROM channel_link_codes
WHERE token = ?1
`

func (q *Queries) GetChannelLinkCodeByToken(ctx context.Context, token string) (ChannelLinkCode, error) {
	row := q.db.QueryRowContext(ctx, getChannelLinkCodeByToken, token)
	var i ChannelLinkCode
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ChannelType,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedChannelIdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const listChannelIdentityBindings = `-- name: ListChannelIdentityBindings :many
SELECT
  b.id,
  b.user_id,
  b.channel_identity_id,
  b.created_at,
  b.updated_at,
  ci.channel_type,
  ci.channel_subject_id,
  ci.display_name AS channel_identity_display_name,
  ci.avatar_url AS channel_identity_avatar_url
FROM user_channel_identity_bindings b
LEFT JOIN channel_identities ci ON ci.id = b.channel_identity_id
ORDER BY b.created_at DESC
`

type ListChannelIdentityBindingsRow struct {
	ID                         string         `json:"id"`
	UserID                     string         `json:"user_id"`
	ChannelIdentityID          string         `json:"channel_identity_id"`
	CreatedAt                  string         `json:"created_at"`
	UpdatedAt                  string         `json:"updated_at"`
	ChannelType                sql.NullString `json:"channel_type"`
	ChannelSubjectID           sql.NullString `json:"channel_subject_id"`
	ChannelIdentityDisplayName sql.NullString `json:"channel_identity_display_name"`
	ChannelIdentityAvatarUrl   sql.NullString `json:"channel_identity_avatar_url"`
}

func (q *Queries) ListChannelIdentityBindings(ctx context.Context) ([]ListChannelIdentityBindingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelIdentityBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelIdentityBindingsRow
	for rows.Next() {
		var i ListChannelIdentityBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelIdentityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelType,
			&i.ChannelSubjectID,
			&i.ChannelIdentityDisplayName,
			&i.ChannelIdentityAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelIdentityBindingsForBot = `-- name: ListChannelIdentityBindingsForBot :many
SELECT DISTINCT
  b.id,
  b.user_id,
  b.channel_identity_id,
  b.created_at,
  b.updated_at,
  ci.channel_type,
  ci.channel_subject_id,
  ci.display_name AS channel_identity_display_name,
  ci.avatar_url AS channel_identity_avatar_url
FROM user_channel_identity_bindings b
INNER JOIN bot_user_grants g ON g.user_id = b.user_id AND g.bot_id = ?1 AND g.subject_type = 'user'
LEFT JOIN channel_identities ci ON ci.id = b.channel_identity_id
ORDER BY b.created_at DESC
`

type ListChannelIdentityBindingsForBotRow struct {
	ID                         string         `json:"id"`
	UserID                     string         `json:"user_id"`
	ChannelIdentityID          string         `json:"channel_identity_id"`
	CreatedAt                  string         `json:"created_at"`
	UpdatedAt                  string         `json:"updated_at"`
	ChannelType                sql.NullString `json:"channel_type"`
	ChannelSubjectID           sql.NullString `json:"channel_subject_id"`
	ChannelIdentityDisplayName sql.NullString `json:"channel_identity_display_name"`
	ChannelIdentityAvatarUrl   sql.NullString `json:"channel_identity_avatar_url"`
}

func (q *Queries) ListChannelIdentityBindingsForBot(ctx context.Context, botID string) ([]ListChannelIdentityBindingsForBotRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelIdentityBindingsForBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelIdentityBindingsForBotRow
	for rows.Next() {
		var i ListChannelIdentityBindingsForBotRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelIdentityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelType,
			&i.ChannelSubjectID,
			&i.ChannelIdentityDisplayName,
			&i.ChannelIdentityAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelIdentityBindingsForUser = `-- name: ListChannelIdentityBindingsForUser :many
SELECT
  b.id,
  b.user_id,
  b.channel_identity_id,
  b.created_at,
  b.updated_at,
  ci.channel_type,
  ci.channel_subject_id,
  ci.display_name AS channel_identity_display_name,
  ci.avatar_url AS channel_identity_avatar_url
FROM user_channel_identity_bindings b
LEFT JOIN channel_identities ci ON ci.id = b.channel_identity_id
WHERE b.user_id = ?1
ORDER BY b.created_at DESC
`

type ListChannelIdentityBindingsForUserRow struct {
	ID                         string         `json:"id"`
	UserID                     string         `json:"user_id"`
	ChannelIdentityID          string         `json:"channel_identity_id"`
	CreatedAt                  string         `json:"created_at"`
	UpdatedAt                  string         `json:"updated_at"`
	ChannelType                sql.NullString `json:"channel_type"`
	ChannelSubjectID           sql.NullString `json:"channel_subject_id"`
	ChannelIdentityDisplayName sql.NullString `json:"channel_identity_display_name"`
	ChannelIdentityAvatarUrl   sql.NullString `json:"channel_identity_avatar_url"`
}

func (q *Queries) ListChannelIdentityBindingsForUser(ctx context.Context, userID string) ([]ListChannelIdentityBindingsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelIdentityBindingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelIdentityBindingsForUserRow
	for rows.Next() {
		var i ListChannelIdentityBindingsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelIdentityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelType,
			&i.ChannelSubjectID,
			&i.ChannelIdentityDisplayName,
			&i.ChannelIdentityAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDsByChannelIdentity = `-- name: ListUserIDsByChannelIdentity :many
SELECT user_id
FROM user_channel_identity_bindings
WHERE channel_identity_id = ?1
`

func (q *Queries) ListUserIDsByChannelIdentity(ctx context.Context, channelIdentityID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserIDsByChannelIdentity, channelIdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChannelLinkCodeConsumed = `-- name: MarkChannelLinkCodeConsumed :one
UPDATE channel_link_codes
SET consumed_at = CURRENT_TIMESTAMP,
    consumed_channel_identity_id = ?1
WHERE token = ?2 AND consumed_at IS NULL AND datetime(expires_at) > CURRENT_TIMESTAMP
RETURNING token, user_id, channel_type, expires_at, consumed_at, consumed_channel_identity_id, created_at
`

type MarkChannelLinkCodeConsumedParams struct {
	ConsumedChannelIdentityID sql.NullString `json:"consumed_channel_identity_id"`
	Token                     string         `json:"token"`
}

func (q *Queries) MarkChannelLinkCodeConsumed(ctx context.Context, arg MarkChannelLinkCodeConsumedParams) (ChannelLinkCode, error) {
	row := q.db.QueryRowContext(ctx, markChannelLinkCodeConsumed, arg.ConsumedChannelIdentityID, arg.Token)
	var i ChannelLinkCode
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ChannelType,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedChannelIdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUserChannelIdentityBinding = `-- name: UpsertUserChannelIdentityBinding :one
INSERT INTO user_channel_identity_bindings (id, user_id, channel_identity_id)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2
)
ON CONFLICT (user_id, channel_identity_id) DO UPDATE
  SET updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, channel_identity_id, created_at, updated_at
`

type UpsertUserChannelIdentityBindingParams struct {
	UserID            string `json:"user_id"`
	ChannelIdentityID string `json:"channel_identity_id"`
}

func (q *Queries) UpsertUserChannelIdentityBinding(ctx context.Context, arg UpsertUserChannelIdentityBindingParams) (UserChannelIdentityBinding, error) {
	row := q.db.QueryRowContext(ctx, upsertUserChannelIdentityBinding, arg.UserID, arg.ChannelIdentityID)
	var i UserChannelIdentityBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelIdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
