// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel_identities.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createChannelIdentity = `-- name: CreateChannelIdentity :one
INSERT INTO channel_identities (id, channel_type, channel_subject_id, display_name, avatar_url, metadata)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5
)
RETURNING id, channel_type, channel_subject_id, display_name, avatar_url, metadata, created_at, updated_at
`

type CreateChannelIdentityParams struct {
	ChannelType      string         `json:"channel_type"`
	ChannelSubjectID string         `json:"channel_subject_id"`
	DisplayName      sql.NullString `json:"display_name"`
	AvatarUrl        sql.NullString `json:"avatar_url"`
	Metadata         string         `json:"metadata"`
}

func (q *Queries) CreateChannelIdentity(ctx context.Context, arg CreateChannelIdentityParams) (ChannelIdentity, error) {
	row := q.db.QueryRowContext(ctx, createChannelIdentity,
		arg.ChannelType,
		arg.ChannelSubjectID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Metadata,
	)
	var i ChannelIdentity
	err := row.Scan(
		&i.ID,
		&i.ChannelType,
		&i.ChannelSubjectID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelIdentityByChannelSubject = `-- name: GetChannelIdentityByChannelSubject :one
SELECT id, channel_type, channel_subject_id, display_name, avatar_url, metadata, created_at, updated_at
FROM channel_identities
WHERE channel_type = ?1 AND channel_subject_id = ?2
`

type GetChannelIdentityByChannelSubjectParams struct {
	ChannelType      string `json:"channel_type"`
	ChannelSubjectID string `json:"channel_subject_id"`
}

func (q *Queries) GetChannelIdentityByChannelSubject(ctx context.Context, arg GetChannelIdentityByChannelSubjectParams) (ChannelIdentity, error) {
	row := q.db.QueryRowContext(ctx, getChannelIdentityByChannelSubject, arg.ChannelType, arg.ChannelSubjectID)
	var i ChannelIdentity
	err := row.Scan(
		&i.ID,
		&i.ChannelType,
		&i.ChannelSubjectID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelIdentityByID = `-- name: GetChannelIdentityByID :one
SELECT id, channel_type, channel_subject_id, display_name, avatar_url, metadata, created_at, updated_at
FROM channel_identities
WHERE id = ?1
`

func (q *Queries) GetChannelIdentityByID(ctx context.Context, id string) (ChannelIdentity, error) {
	row := q.db.QueryRowContext(ctx, getChannelIdentityByID, id)
	var i ChannelIdentity
	err := row.Scan(
		&i.ID,
		&i.ChannelType,
		&i.ChannelSubjectID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelIdentityByIDForUpdate = `-- name: GetChannelIdentityByIDForUpdate :one
SELECT id, channel_type, channel_subject_id, display_name, avatar_url, metadata, created_at, updated_at
FROM channel_identities
WHERE id = ?1
`

func (q *Queries) GetChannelIdentityByIDForUpdate(ctx context.Context, id string) (ChannelIdentity, error) {
	row := q.db.QueryRowContext(ctx, getChannelIdentityByIDForUpdate, id)
	var i ChannelIdentity
	err := row.Scan(
		&i.ID,
		&i.ChannelType,
		&i.ChannelSubjectID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchChannelIdentities = `-- name: SearchChannelIdentities :many
SELECT
  ci.id,
  ci.channel_type,
  ci.channel_subject_id,
  ci.display_name,
  ci.avatar_url,
  ci.metadata,
  ci.created_at,
  ci.updated_at
FROM channel_identities ci
WHERE
  ?1 = ''
  OR lower(ci.channel_type) LIKE '%' || lower(?1) || '%'
  OR lower(ci.channel_subject_id) LIKE '%' || lower(?1) || '%'
  OR lower(COALESCE(ci.display_name, '')) LIKE '%' || lower(?1) || '%'
ORDER BY ci.updated_at DESC
LIMIT ?2
`

type SearchChannelIdentitiesParams struct {
	Query      interface{} `json:"query"`
	LimitCount int64       `json:"limit_count"`
}

func (q *Queries) SearchChannelIdentities(ctx context.Context, arg SearchChannelIdentitiesParams) ([]ChannelIdentity, error) {
	rows, err := q.db.QueryContext(ctx, searchChannelIdentities, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelIdentity
	for rows.Next() {
		var i ChannelIdentity
		if err := rows.Scan(
			&i.ID,
			&i.ChannelType,
			&i.ChannelSubjectID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChannelIdentityByChannelSubject = `-- name: UpsertChannelIdentityByChannelSubject :one
INSERT INTO channel_identities (id, channel_type, channel_subject_id, display_name, avatar_url, metadata)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5
)
ON CONFLICT (channel_type, channel_subject_id)
DO UPDATE SET
  display_name = COALESCE(NULLIF(EXCLUDED.display_name, ''), channel_identities.display_name),
  avatar_url = COALESCE(NULLIF(EXCLUDED.avatar_url, ''), channel_identities.avatar_url),
  metadata = EXCLUDED.metadata,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, channel_type, channel_subject_id, display_name, avatar_url, metadata, created_at, updated_at
`

type UpsertChannelIdentityByChannelSubjectParams struct {
	ChannelType      string         `json:"channel_type"`
	ChannelSubjectID string         `json:"channel_subject_id"`
	DisplayName      sql.NullString `json:"display_name"`
	AvatarUrl        sql.NullString `json:"avatar_url"`
	Metadata         string         `json:"metadata"`
}

func (q *Queries) UpsertChannelIdentityByChannelSubject(ctx context.Context, arg UpsertChannelIdentityByChannelSubjectParams) (ChannelIdentity, error) {
	row := q.db.QueryRowContext(ctx, upsertChannelIdentityByChannelSubject,
		arg.ChannelType,
		arg.ChannelSubjectID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Metadata,
	)
	var i ChannelIdentity
	err := row.Scan(
		&i.ID,
		&i.ChannelType,
		&i.ChannelSubjectID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
