// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel_routes.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createChatRoute = `-- name: CreateChatRoute :one
INSERT INTO bot_channel_routes (
  id, bot_id, channel_type, channel_config_id, external_conversation_id, external_thread_id,
  conversation_type, default_reply_target, metadata
)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
)
RETURNING
  id,
  bot_id AS chat_id,
  bot_id,
  channel_type AS platform,
  channel_config_id,
  external_conversation_id AS conversation_id,
  external_thread_id AS thread_id,
  conversation_type,
  default_reply_target AS reply_target,
  active_session_id,
  metadata,
  created_at,
  updated_at
`

type CreateChatRouteParams struct {
	BotID            string         `json:"bot_id"`
	Platform         string         `json:"platform"`
	ChannelConfigID  sql.NullString `json:"channel_config_id"`
	ConversationID   string         `json:"conversation_id"`
	ThreadID         sql.NullString `json:"thread_id"`
	ConversationType sql.NullString `json:"conversation_type"`
	ReplyTarget      sql.NullString `json:"reply_target"`
	Metadata         string         `json:"metadata"`
}

type CreateChatRouteRow struct {
	ID                     string         `json:"id"`
	BotID                  string         `json:"bot_id"`
	BotID_2                string         `json:"bot_id_2"`
	ChannelType            string         `json:"channel_type"`
	ChannelConfigID        sql.NullString `json:"channel_config_id"`
	ExternalConversationID string         `json:"external_conversation_id"`
	ExternalThreadID       sql.NullString `json:"external_thread_id"`
	ConversationType       sql.NullString `json:"conversation_type"`
	DefaultReplyTarget     sql.NullString `json:"default_reply_target"`
	ActiveSessionID        sql.NullString `json:"active_session_id"`
	Metadata               string         `json:"metadata"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
}

func (q *Queries) CreateChatRoute(ctx context.Context, arg CreateChatRouteParams) (CreateChatRouteRow, error) {
	row := q.db.QueryRowContext(ctx, createChatRoute,
		arg.BotID,
		arg.Platform,
		arg.ChannelConfigID,
		arg.ConversationID,
		arg.ThreadID,
		arg.ConversationType,
		arg.ReplyTarget,
		arg.Metadata,
	)
	var i CreateChatRouteRow
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.BotID_2,
		&i.ChannelType,
		&i.ChannelConfigID,
		&i.ExternalConversationID,
		&i.ExternalThreadID,
		&i.ConversationType,
		&i.DefaultReplyTarget,
		&i.ActiveSessionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChatRoute = `-- name: DeleteChatRoute :exec
DELETE FROM bot_channel_routes WHERE id = ?1
`

func (q *Queries) DeleteChatRoute(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteChatRoute, id)
	return err
}

const findChatRoute = `-- name: FindChatRoute :one
SELECT
  id,
  bot_id AS chat_id,
  bot_id,
  channel_type AS platform,
  channel_config_id,
  external_conversation_id AS conversation_id,
  external_thread_id AS thread_id,
  conversation_type,
  default_reply_target AS reply_target,
  active_session_id,
  metadata,
  created_at,
  updated_at
FROM bot_channel_routes
WHERE bot_id = ?1
  AND channel_type = ?2
  AND external_conversation_id = ?3
  AND COALESCE(external_thread_id, '') = COALESCE(?4, '')
LIMIT 1
`

type FindChatRouteParams struct {
	BotID          string         `json:"bot_id"`
	Platform       string         `json:"platform"`
	ConversationID string         `json:"conversation_id"`
	ThreadID       sql.NullString `json:"thread_id"`
}

type FindChatRouteRow struct {
	ID               string         `json:"id"`
	ChatID           string         `json:"chat_id"`
	BotID            string         `json:"bot_id"`
	Platform         string         `json:"platform"`
	ChannelConfigID  sql.NullString `json:"channel_config_id"`
	ConversationID   string         `json:"conversation_id"`
	ThreadID         sql.NullString `json:"thread_id"`
	ConversationType sql.NullString `json:"conversation_type"`
	ReplyTarget      sql.NullString `json:"reply_target"`
	ActiveSessionID  sql.NullString `json:"active_session_id"`
	Metadata         string         `json:"metadata"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) FindChatRoute(ctx context.Context, arg FindChatRouteParams) (FindChatRouteRow, error) {
	row := q.db.QueryRowContext(ctx, findChatRoute,
		arg.BotID,
		arg.Platform,
		arg.ConversationID,
		arg.ThreadID,
	)
	var i FindChatRouteRow
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.BotID,
		&i.Platform,
		&i.ChannelConfigID,
		&i.ConversationID,
		&i.ThreadID,
		&i.ConversationType,
		&i.ReplyTarget,
		&i.ActiveSessionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatRouteByID = `-- name: GetChatRouteByID :one
SELECT
  id,
  bot_id AS chat_id,
  bot_id,
  channel_type AS platform,
  channel_config_id,
  external_conversation_id AS conversation_id,
  external_thread_id AS thread_id,
  conversation_type,
  default_reply_target AS reply_target,
  active_session_id,
  metadata,
  created_at,
  updated_at
FROM bot_channel_routes
WHERE id = ?1
`

type GetChatRouteByIDRow struct {
	ID               string         `json:"id"`
	ChatID           string         `json:"chat_id"`
	BotID            string         `json:"bot_id"`
	Platform         string         `json:"platform"`
	ChannelConfigID  sql.NullString `json:"channel_config_id"`
	ConversationID   string         `json:"conversation_id"`
	ThreadID         sql.NullString `json:"thread_id"`
	ConversationType sql.NullString `json:"conversation_type"`
	ReplyTarget      sql.NullString `json:"reply_target"`
	ActiveSessionID  sql.NullString `json:"active_session_id"`
	Metadata         string         `json:"metadata"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) GetChatRouteByID(ctx context.Context, id string) (GetChatRouteByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getChatRouteByID, id)
	var i GetChatRouteByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.BotID,
		&i.Platform,
		&i.ChannelConfigID,
		&i.ConversationID,
		&i.ThreadID,
		&i.ConversationType,
		&i.ReplyTarget,
		&i.ActiveSessionID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChatRoutes = `-- name: ListChatRoutes :many
SELECT
  id,
  bot_id AS chat_id,
  bot_id,
  channel_type AS platform,
  channel_config_id,
  external_conversation_id AS conversation_id,
  external_thread_id AS thread_id,
  conversation_type,
  default_reply_target AS reply_target,
  active_session_id,
  metadata,
  created_at,
  updated_at
FROM bot_channel_routes
WHERE bot_id = ?1
ORDER BY created_at ASC
`

type ListChatRoutesRow struct {
	ID               string         `json:"id"`
	ChatID           string         `json:"chat_id"`
	BotID            string         `json:"bot_id"`
	Platform         string         `json:"platform"`
	ChannelConfigID  sql.NullString `json:"channel_config_id"`
	ConversationID   string         `json:"conversation_id"`
	ThreadID         sql.NullString `json:"thread_id"`
	ConversationType sql.NullString `json:"conversation_type"`
	ReplyTarget      sql.NullString `json:"reply_target"`
	ActiveSessionID  sql.NullString `json:"active_session_id"`
	Metadata         string         `json:"metadata"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) ListChatRoutes(ctx context.Context, chatID string) ([]ListChatRoutesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatRoutes, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatRoutesRow
	for rows.Next() {
		var i ListChatRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.BotID,
			&i.Platform,
			&i.ChannelConfigID,
			&i.ConversationID,
			&i.ThreadID,
			&i.ConversationType,
			&i.ReplyTarget,
			&i.ActiveSessionID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRouteActiveSession = `-- name: SetRouteActiveSession :exec
UPDATE bot_channel_routes
SET active_session_id = ?1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type SetRouteActiveSessionParams struct {
	ActiveSessionID sql.NullString `json:"active_session_id"`
	ID              string         `json:"id"`
}

func (q *Queries) SetRouteActiveSession(ctx context.Context, arg SetRouteActiveSessionParams) error {
	_, err := q.db.ExecContext(ctx, setRouteActiveSession, arg.ActiveSessionID, arg.ID)
	return err
}

const updateChatRouteMetadata = `-- name: UpdateChatRouteMetadata :exec
UPDATE bot_channel_routes
SET metadata = ?1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateChatRouteMetadataParams struct {
	Metadata string `json:"metadata"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateChatRouteMetadata(ctx context.Context, arg UpdateChatRouteMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateChatRouteMetadata, arg.Metadata, arg.ID)
	return err
}

const updateChatRouteReplyTarget = `-- name: UpdateChatRouteReplyTarget :exec
UPDATE bot_channel_routes
SET default_reply_target = ?1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateChatRouteReplyTargetParams struct {
	ReplyTarget sql.NullString `json:"reply_target"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateChatRouteReplyTarget(ctx context.Context, arg UpdateChatRouteReplyTargetParams) error {
	_, err := q.db.ExecContext(ctx, updateChatRouteReplyTarget, arg.ReplyTarget, arg.ID)
	return err
}
