// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compaction_logs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const completeCompactionLog = `-- name: CompleteCompactionLog :one
UPDATE bot_history_message_compacts
SET status = ?1,
    summary = ?2,
    message_count = ?3,
    error_message = ?4,
    usage = ?5,
    model_id = ?6,
    completed_at = CURRENT_TIMESTAMP
WHERE id = ?7
RETURNING id, bot_id, session_id, status, summary, message_count, error_message, usage, model_id, started_at, completed_at
`

type CompleteCompactionLogParams struct {
	Status       string         `json:"status"`
	Summary      string         `json:"summary"`
	MessageCount int64          `json:"message_count"`
	ErrorMessage string         `json:"error_message"`
	Usage        sql.NullString `json:"usage"`
	ModelID      sql.NullString `json:"model_id"`
	ID           string         `json:"id"`
}

func (q *Queries) CompleteCompactionLog(ctx context.Context, arg CompleteCompactionLogParams) (BotHistoryMessageCompact, error) {
	row := q.db.QueryRowContext(ctx, completeCompactionLog,
		arg.Status,
		arg.Summary,
		arg.MessageCount,
		arg.ErrorMessage,
		arg.Usage,
		arg.ModelID,
		arg.ID,
	)
	var i BotHistoryMessageCompact
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.Summary,
		&i.MessageCount,
		&i.ErrorMessage,
		&i.Usage,
		&i.ModelID,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countCompactionLogsByBot = `-- name: CountCompactionLogsByBot :one
SELECT count(*) FROM bot_history_message_compacts WHERE bot_id = ?1
`

func (q *Queries) CountCompactionLogsByBot(ctx context.Context, botID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompactionLogsByBot, botID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompactionLog = `-- name: CreateCompactionLog :one
INSERT INTO bot_history_message_compacts (id, bot_id, session_id)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2
)
RETURNING id, bot_id, session_id, status, summary, message_count, error_message, usage, model_id, started_at, completed_at
`

type CreateCompactionLogParams struct {
	BotID     string         `json:"bot_id"`
	SessionID sql.NullString `json:"session_id"`
}

func (q *Queries) CreateCompactionLog(ctx context.Context, arg CreateCompactionLogParams) (BotHistoryMessageCompact, error) {
	row := q.db.QueryRowContext(ctx, createCompactionLog, arg.BotID, arg.SessionID)
	var i BotHistoryMessageCompact
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.Summary,
		&i.MessageCount,
		&i.ErrorMessage,
		&i.Usage,
		&i.ModelID,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteCompactionLogsByBot = `-- name: DeleteCompactionLogsByBot :exec
DELETE FROM bot_history_message_compacts WHERE bot_id = ?1
`

func (q *Queries) DeleteCompactionLogsByBot(ctx context.Context, botID string) error {
	_, err := q.db.ExecContext(ctx, deleteCompactionLogsByBot, botID)
	return err
}

const getCompactionLogByID = `-- name: GetCompactionLogByID :one
SELECT id, bot_id, session_id, status, summary, message_count, error_message, usage, model_id, started_at, completed_at
FROM bot_history_message_compacts
WHERE id = ?1
`

func (q *Queries) GetCompactionLogByID(ctx context.Context, id string) (BotHistoryMessageCompact, error) {
	row := q.db.QueryRowContext(ctx, getCompactionLogByID, id)
	var i BotHistoryMessageCompact
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.Summary,
		&i.MessageCount,
		&i.ErrorMessage,
		&i.Usage,
		&i.ModelID,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listCompactionLogsByBot = `-- name: ListCompactionLogsByBot :many
SELECT id, bot_id, session_id, status, summary, message_count, error_message, usage, model_id, started_at, completed_at
FROM bot_history_message_compacts
WHERE bot_id = ?1
ORDER BY started_at DESC
LIMIT ?3 OFFSET ?2
`

type ListCompactionLogsByBotParams struct {
	BotID string `json:"bot_id"`
	Off   int64  `json:"off"`
	Lim   int64  `json:"lim"`
}

func (q *Queries) ListCompactionLogsByBot(ctx context.Context, arg ListCompactionLogsByBotParams) ([]BotHistoryMessageCompact, error) {
	rows, err := q.db.QueryContext(ctx, listCompactionLogsByBot, arg.BotID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotHistoryMessageCompact
	for rows.Next() {
		var i BotHistoryMessageCompact
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.Status,
			&i.Summary,
			&i.MessageCount,
			&i.ErrorMessage,
			&i.Usage,
			&i.ModelID,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompactionLogsBySession = `-- name: ListCompactionLogsBySession :many
SELECT id, bot_id, session_id, status, summary, message_count, error_message, usage, model_id, started_at, completed_at
FROM bot_history_message_compacts
WHERE session_id = ?1
ORDER BY started_at ASC
`

func (q *Queries) ListCompactionLogsBySession(ctx context.Context, sessionID sql.NullString) ([]BotHistoryMessageCompact, error) {
	rows, err := q.db.QueryContext(ctx, listCompactionLogsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotHistoryMessageCompact
	for rows.Next() {
		var i BotHistoryMessageCompact
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.Status,
			&i.Summary,
			&i.MessageCount,
			&i.ErrorMessage,
			&i.Usage,
			&i.ModelID,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
