// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_oauth_tokens.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteEmailOAuthToken = `-- name: DeleteEmailOAuthToken :exec
DELETE FROM email_oauth_tokens WHERE email_provider_id = ?1
`

func (q *Queries) DeleteEmailOAuthToken(ctx context.Context, emailProviderID string) error {
	_, err := q.db.ExecContext(ctx, deleteEmailOAuthToken, emailProviderID)
	return err
}

const getEmailOAuthTokenByProvider = `-- name: GetEmailOAuthTokenByProvider :one
SELECT id, email_provider_id, email_address, access_token, refresh_token, expires_at, scope, state, created_at, updated_at FROM email_oauth_tokens WHERE email_provider_id = ?1
`

func (q *Queries) GetEmailOAuthTokenByProvider(ctx context.Context, emailProviderID string) (EmailOauthToken, error) {
	row := q.db.QueryRowContext(ctx, getEmailOAuthTokenByProvider, emailProviderID)
	var i EmailOauthToken
	err := row.Scan(
		&i.ID,
		&i.EmailProviderID,
		&i.EmailAddress,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scope,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailOAuthTokenByState = `-- name: GetEmailOAuthTokenByState :one
SELECT id, email_provider_id, email_address, access_token, refresh_token, expires_at, scope, state, created_at, updated_at FROM email_oauth_tokens WHERE state = ?1 AND state != ''
`

func (q *Queries) GetEmailOAuthTokenByState(ctx context.Context, state string) (EmailOauthToken, error) {
	row := q.db.QueryRowContext(ctx, getEmailOAuthTokenByState, state)
	var i EmailOauthToken
	err := row.Scan(
		&i.ID,
		&i.EmailProviderID,
		&i.EmailAddress,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scope,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmailOAuthState = `-- name: UpdateEmailOAuthState :exec
INSERT INTO email_oauth_tokens (id, email_provider_id, state)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2
)
ON CONFLICT (email_provider_id) DO UPDATE SET
  state      = EXCLUDED.state,
  updated_at = CURRENT_TIMESTAMP
`

type UpdateEmailOAuthStateParams struct {
	EmailProviderID string `json:"email_provider_id"`
	State           string `json:"state"`
}

func (q *Queries) UpdateEmailOAuthState(ctx context.Context, arg UpdateEmailOAuthStateParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailOAuthState, arg.EmailProviderID, arg.State)
	return err
}

const upsertEmailOAuthToken = `-- name: UpsertEmailOAuthToken :one
INSERT INTO email_oauth_tokens (id, email_provider_id, email_address, access_token, refresh_token, expires_at, scope, state)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7
)
ON CONFLICT (email_provider_id) DO UPDATE SET
  email_address  = EXCLUDED.email_address,
  access_token   = EXCLUDED.access_token,
  refresh_token  = EXCLUDED.refresh_token,
  expires_at     = EXCLUDED.expires_at,
  scope          = EXCLUDED.scope,
  state          = EXCLUDED.state,
  updated_at     = CURRENT_TIMESTAMP
RETURNING id, email_provider_id, email_address, access_token, refresh_token, expires_at, scope, state, created_at, updated_at
`

type UpsertEmailOAuthTokenParams struct {
	EmailProviderID string         `json:"email_provider_id"`
	EmailAddress    string         `json:"email_address"`
	AccessToken     string         `json:"access_token"`
	RefreshToken    string         `json:"refresh_token"`
	ExpiresAt       sql.NullString `json:"expires_at"`
	Scope           string         `json:"scope"`
	State           string         `json:"state"`
}

func (q *Queries) UpsertEmailOAuthToken(ctx context.Context, arg UpsertEmailOAuthTokenParams) (EmailOauthToken, error) {
	row := q.db.QueryRowContext(ctx, upsertEmailOAuthToken,
		arg.EmailProviderID,
		arg.EmailAddress,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.Scope,
		arg.State,
	)
	var i EmailOauthToken
	err := row.Scan(
		&i.ID,
		&i.EmailProviderID,
		&i.EmailAddress,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scope,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
