// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createMCPConnection = `-- name: CreateMCPConnection :one
INSERT INTO mcp_connections (id, bot_id, name, type, config, is_active, auth_type)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6
)
RETURNING id, bot_id, name, type, config, is_active, status, tools_cache, last_probed_at, status_message, auth_type,
          managed_by_plugin_installation_id, managed_resource_key, visible, metadata, created_at, updated_at
`

type CreateMCPConnectionParams struct {
	BotID    string `json:"bot_id"`
	Name     string `json:"name"`
	Type     string `json:"type"`
	Config   string `json:"config"`
	IsActive int64  `json:"is_active"`
	AuthType string `json:"auth_type"`
}

func (q *Queries) CreateMCPConnection(ctx context.Context, arg CreateMCPConnectionParams) (McpConnection, error) {
	row := q.db.QueryRowContext(ctx, createMCPConnection,
		arg.BotID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.IsActive,
		arg.AuthType,
	)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.IsActive,
		&i.Status,
		&i.ToolsCache,
		&i.LastProbedAt,
		&i.StatusMessage,
		&i.AuthType,
		&i.ManagedByPluginInstallationID,
		&i.ManagedResourceKey,
		&i.Visible,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createManagedMCPConnection = `-- name: CreateManagedMCPConnection :one
INSERT INTO mcp_connections (
  id, bot_id, name, type, config, is_active, auth_type,
  managed_by_plugin_installation_id, managed_resource_key, visible, metadata
)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10
)
RETURNING id, bot_id, name, type, config, is_active, status, tools_cache, last_probed_at, status_message, auth_type,
          managed_by_plugin_installation_id, managed_resource_key, visible, metadata, created_at, updated_at
`

type CreateManagedMCPConnectionParams struct {
	BotID                         string         `json:"bot_id"`
	Name                          string         `json:"name"`
	Type                          string         `json:"type"`
	Config                        string         `json:"config"`
	IsActive                      int64          `json:"is_active"`
	AuthType                      string         `json:"auth_type"`
	ManagedByPluginInstallationID sql.NullString `json:"managed_by_plugin_installation_id"`
	ManagedResourceKey            string         `json:"managed_resource_key"`
	Visible                       int64          `json:"visible"`
	Metadata                      string         `json:"metadata"`
}

func (q *Queries) CreateManagedMCPConnection(ctx context.Context, arg CreateManagedMCPConnectionParams) (McpConnection, error) {
	row := q.db.QueryRowContext(ctx, createManagedMCPConnection,
		arg.BotID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.IsActive,
		arg.AuthType,
		arg.ManagedByPluginInstallationID,
		arg.ManagedResourceKey,
		arg.Visible,
		arg.Metadata,
	)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.IsActive,
		&i.Status,
		&i.ToolsCache,
		&i.LastProbedAt,
		&i.StatusMessage,
		&i.AuthType,
		&i.ManagedByPluginInstallationID,
		&i.ManagedResourceKey,
		&i.Visible,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMCPConnection = `-- name: DeleteMCPConnection :exec
DELETE FROM mcp_connections
WHERE bot_id = ?1 AND id = ?2
`

type DeleteMCPConnectionParams struct {
	BotID string `json:"bot_id"`
	ID    string `json:"id"`
}

func (q *Queries) DeleteMCPConnection(ctx context.Context, arg DeleteMCPConnectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteMCPConnection, arg.BotID, arg.ID)
	return err
}

const deleteMCPConnectionsByPlugin = `-- name: DeleteMCPConnectionsByPlugin :exec
DELETE FROM mcp_connections
WHERE bot_id = ?1 AND managed_by_plugin_installation_id = ?2
`

type DeleteMCPConnectionsByPluginParams struct {
	BotID                         string         `json:"bot_id"`
	ManagedByPluginInstallationID sql.NullString `json:"managed_by_plugin_installation_id"`
}

func (q *Queries) DeleteMCPConnectionsByPlugin(ctx context.Context, arg DeleteMCPConnectionsByPluginParams) error {
	_, err := q.db.ExecContext(ctx, deleteMCPConnectionsByPlugin, arg.BotID, arg.ManagedByPluginInstallationID)
	return err
}

const getMCPConnectionByID = `-- name: GetMCPConnectionByID :one
SELECT id, bot_id, name, type, config, is_active, status, tools_cache, last_probed_at, status_message, auth_type,
       managed_by_plugin_installation_id, managed_resource_key, visible, metadata, created_at, updated_at
FROM mcp_connections
WHERE bot_id = ?1 AND id = ?2
LIMIT 1
`

type GetMCPConnectionByIDParams struct {
	BotID string `json:"bot_id"`
	ID    string `json:"id"`
}

func (q *Queries) GetMCPConnectionByID(ctx context.Context, arg GetMCPConnectionByIDParams) (McpConnection, error) {
	row := q.db.QueryRowContext(ctx, getMCPConnectionByID, arg.BotID, arg.ID)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.IsActive,
		&i.Status,
		&i.ToolsCache,
		&i.LastProbedAt,
		&i.StatusMessage,
		&i.AuthType,
		&i.ManagedByPluginInstallationID,
		&i.ManagedResourceKey,
		&i.Visible,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMCPConnectionsByBotID = `-- name: ListMCPConnectionsByBotID :many
SELECT id, bot_id, name, type, config, is_active, status, tools_cache, last_probed_at, status_message, auth_type,
       managed_by_plugin_installation_id, managed_resource_key, visible, metadata, created_at, updated_at
FROM mcp_connections
WHERE bot_id = ?1
ORDER BY created_at DESC
`

func (q *Queries) ListMCPConnectionsByBotID(ctx context.Context, botID string) ([]McpConnection, error) {
	rows, err := q.db.QueryContext(ctx, listMCPConnectionsByBotID, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpConnection
	for rows.Next() {
		var i McpConnection
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.IsActive,
			&i.Status,
			&i.ToolsCache,
			&i.LastProbedAt,
			&i.StatusMessage,
			&i.AuthType,
			&i.ManagedByPluginInstallationID,
			&i.ManagedResourceKey,
			&i.Visible,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMCPConnection = `-- name: UpdateMCPConnection :one
UPDATE mcp_connections
SET name = ?1,
    type = ?2,
    config = ?3,
    is_active = ?4,
    auth_type = ?5,
    updated_at = CURRENT_TIMESTAMP
WHERE bot_id = ?6 AND id = ?7
RETURNING id, bot_id, name, type, config, is_active, status, tools_cache, last_probed_at, status_message, auth_type,
          managed_by_plugin_installation_id, managed_resource_key, visible, metadata, created_at, updated_at
`

type UpdateMCPConnectionParams struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Config   string `json:"config"`
	IsActive int64  `json:"is_active"`
	AuthType string `json:"auth_type"`
	BotID    string `json:"bot_id"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateMCPConnection(ctx context.Context, arg UpdateMCPConnectionParams) (McpConnection, error) {
	row := q.db.QueryRowContext(ctx, updateMCPConnection,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.IsActive,
		arg.AuthType,
		arg.BotID,
		arg.ID,
	)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.IsActive,
		&i.Status,
		&i.ToolsCache,
		&i.LastProbedAt,
		&i.StatusMessage,
		&i.AuthType,
		&i.ManagedByPluginInstallationID,
		&i.ManagedResourceKey,
		&i.Visible,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMCPConnectionActive = `-- name: UpdateMCPConnectionActive :exec
UPDATE mcp_connections
SET is_active = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE bot_id = ?2 AND id = ?3
`

type UpdateMCPConnectionActiveParams struct {
	IsActive int64  `json:"is_active"`
	BotID    string `json:"bot_id"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateMCPConnectionActive(ctx context.Context, arg UpdateMCPConnectionActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPConnectionActive, arg.IsActive, arg.BotID, arg.ID)
	return err
}

const updateMCPConnectionAuthType = `-- name: UpdateMCPConnectionAuthType :exec
UPDATE mcp_connections
SET auth_type = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type UpdateMCPConnectionAuthTypeParams struct {
	AuthType string `json:"auth_type"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateMCPConnectionAuthType(ctx context.Context, arg UpdateMCPConnectionAuthTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPConnectionAuthType, arg.AuthType, arg.ID)
	return err
}

const updateMCPConnectionProbeResult = `-- name: UpdateMCPConnectionProbeResult :exec
UPDATE mcp_connections
SET status = ?1,
    tools_cache = ?2,
    last_probed_at = CURRENT_TIMESTAMP,
    status_message = ?3,
    updated_at = CURRENT_TIMESTAMP
WHERE bot_id = ?4 AND id = ?5
`

type UpdateMCPConnectionProbeResultParams struct {
	Status        string `json:"status"`
	ToolsCache    string `json:"tools_cache"`
	StatusMessage string `json:"status_message"`
	BotID         string `json:"bot_id"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateMCPConnectionProbeResult(ctx context.Context, arg UpdateMCPConnectionProbeResultParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPConnectionProbeResult,
		arg.Status,
		arg.ToolsCache,
		arg.StatusMessage,
		arg.BotID,
		arg.ID,
	)
	return err
}

const updateMCPConnectionsActiveByPlugin = `-- name: UpdateMCPConnectionsActiveByPlugin :exec
UPDATE mcp_connections
SET is_active = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE bot_id = ?2 AND managed_by_plugin_installation_id = ?3
`

type UpdateMCPConnectionsActiveByPluginParams struct {
	IsActive                      int64          `json:"is_active"`
	BotID                         string         `json:"bot_id"`
	ManagedByPluginInstallationID sql.NullString `json:"managed_by_plugin_installation_id"`
}

func (q *Queries) UpdateMCPConnectionsActiveByPlugin(ctx context.Context, arg UpdateMCPConnectionsActiveByPluginParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPConnectionsActiveByPlugin, arg.IsActive, arg.BotID, arg.ManagedByPluginInstallationID)
	return err
}

const upsertMCPConnectionByName = `-- name: UpsertMCPConnectionByName :one
INSERT INTO mcp_connections (id, bot_id, name, type, config)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4
)
ON CONFLICT (bot_id, name)
DO UPDATE SET type = EXCLUDED.type,
              config = EXCLUDED.config,
              updated_at = CURRENT_TIMESTAMP
RETURNING id, bot_id, name, type, config, is_active, status, tools_cache, last_probed_at, status_message, auth_type,
          managed_by_plugin_installation_id, managed_resource_key, visible, metadata, created_at, updated_at
`

type UpsertMCPConnectionByNameParams struct {
	BotID  string `json:"bot_id"`
	Name   string `json:"name"`
	Type   string `json:"type"`
	Config string `json:"config"`
}

func (q *Queries) UpsertMCPConnectionByName(ctx context.Context, arg UpsertMCPConnectionByNameParams) (McpConnection, error) {
	row := q.db.QueryRowContext(ctx, upsertMCPConnectionByName,
		arg.BotID,
		arg.Name,
		arg.Type,
		arg.Config,
	)
	var i McpConnection
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.IsActive,
		&i.Status,
		&i.ToolsCache,
		&i.LastProbedAt,
		&i.StatusMessage,
		&i.AuthType,
		&i.ManagedByPluginInstallationID,
		&i.ManagedResourceKey,
		&i.Visible,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
