// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugins.sql

package sqlc

import (
	"context"
)

const createBotPluginInstallation = `-- name: CreateBotPluginInstallation :one
INSERT INTO bot_plugin_installations (
  id, bot_id, plugin_id, plugin_name, version, status, enabled, config, metadata, manifest
)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9
)
ON CONFLICT (bot_id, plugin_id)
DO UPDATE SET plugin_name = EXCLUDED.plugin_name,
              version = EXCLUDED.version,
              status = EXCLUDED.status,
              enabled = EXCLUDED.enabled,
              config = EXCLUDED.config,
              metadata = EXCLUDED.metadata,
              manifest = EXCLUDED.manifest,
              updated_at = CURRENT_TIMESTAMP
RETURNING id, bot_id, plugin_id, plugin_name, version, status, enabled, config, metadata, manifest, installed_at, updated_at
`

type CreateBotPluginInstallationParams struct {
	BotID      string `json:"bot_id"`
	PluginID   string `json:"plugin_id"`
	PluginName string `json:"plugin_name"`
	Version    string `json:"version"`
	Status     string `json:"status"`
	Enabled    int64  `json:"enabled"`
	Config     string `json:"config"`
	Metadata   string `json:"metadata"`
	Manifest   string `json:"manifest"`
}

func (q *Queries) CreateBotPluginInstallation(ctx context.Context, arg CreateBotPluginInstallationParams) (BotPluginInstallation, error) {
	row := q.db.QueryRowContext(ctx, createBotPluginInstallation,
		arg.BotID,
		arg.PluginID,
		arg.PluginName,
		arg.Version,
		arg.Status,
		arg.Enabled,
		arg.Config,
		arg.Metadata,
		arg.Manifest,
	)
	var i BotPluginInstallation
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.PluginID,
		&i.PluginName,
		&i.Version,
		&i.Status,
		&i.Enabled,
		&i.Config,
		&i.Metadata,
		&i.Manifest,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBotPluginInstallation = `-- name: DeleteBotPluginInstallation :exec
DELETE FROM bot_plugin_installations
WHERE bot_id = ?1 AND id = ?2
`

type DeleteBotPluginInstallationParams struct {
	BotID string `json:"bot_id"`
	ID    string `json:"id"`
}

func (q *Queries) DeleteBotPluginInstallation(ctx context.Context, arg DeleteBotPluginInstallationParams) error {
	_, err := q.db.ExecContext(ctx, deleteBotPluginInstallation, arg.BotID, arg.ID)
	return err
}

const deleteBotPluginResources = `-- name: DeleteBotPluginResources :exec
DELETE FROM bot_plugin_resources
WHERE installation_id = ?1
`

func (q *Queries) DeleteBotPluginResources(ctx context.Context, installationID string) error {
	_, err := q.db.ExecContext(ctx, deleteBotPluginResources, installationID)
	return err
}

const getBotPluginInstallationByID = `-- name: GetBotPluginInstallationByID :one
SELECT id, bot_id, plugin_id, plugin_name, version, status, enabled, config, metadata, manifest, installed_at, updated_at
FROM bot_plugin_installations
WHERE bot_id = ?1 AND id = ?2
LIMIT 1
`

type GetBotPluginInstallationByIDParams struct {
	BotID string `json:"bot_id"`
	ID    string `json:"id"`
}

func (q *Queries) GetBotPluginInstallationByID(ctx context.Context, arg GetBotPluginInstallationByIDParams) (BotPluginInstallation, error) {
	row := q.db.QueryRowContext(ctx, getBotPluginInstallationByID, arg.BotID, arg.ID)
	var i BotPluginInstallation
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.PluginID,
		&i.PluginName,
		&i.Version,
		&i.Status,
		&i.Enabled,
		&i.Config,
		&i.Metadata,
		&i.Manifest,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBotPluginInstallations = `-- name: ListBotPluginInstallations :many
SELECT id, bot_id, plugin_id, plugin_name, version, status, enabled, config, metadata, manifest, installed_at, updated_at
FROM bot_plugin_installations
WHERE bot_id = ?1
ORDER BY installed_at DESC
`

func (q *Queries) ListBotPluginInstallations(ctx context.Context, botID string) ([]BotPluginInstallation, error) {
	rows, err := q.db.QueryContext(ctx, listBotPluginInstallations, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotPluginInstallation
	for rows.Next() {
		var i BotPluginInstallation
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.PluginID,
			&i.PluginName,
			&i.Version,
			&i.Status,
			&i.Enabled,
			&i.Config,
			&i.Metadata,
			&i.Manifest,
			&i.InstalledAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotPluginResources = `-- name: ListBotPluginResources :many
SELECT id, installation_id, resource_type, resource_key, resource_id, status, metadata, created_at, updated_at
FROM bot_plugin_resources
WHERE installation_id = ?1
ORDER BY resource_type ASC, resource_key ASC
`

func (q *Queries) ListBotPluginResources(ctx context.Context, installationID string) ([]BotPluginResource, error) {
	rows, err := q.db.QueryContext(ctx, listBotPluginResources, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotPluginResource
	for rows.Next() {
		var i BotPluginResource
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.ResourceType,
			&i.ResourceKey,
			&i.ResourceID,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBotPluginInstallationStatus = `-- name: UpdateBotPluginInstallationStatus :one
UPDATE bot_plugin_installations
SET status = ?1,
    enabled = ?2,
    updated_at = CURRENT_TIMESTAMP
WHERE bot_id = ?3 AND id = ?4
RETURNING id, bot_id, plugin_id, plugin_name, version, status, enabled, config, metadata, manifest, installed_at, updated_at
`

type UpdateBotPluginInstallationStatusParams struct {
	Status  string `json:"status"`
	Enabled int64  `json:"enabled"`
	BotID   string `json:"bot_id"`
	ID      string `json:"id"`
}

func (q *Queries) UpdateBotPluginInstallationStatus(ctx context.Context, arg UpdateBotPluginInstallationStatusParams) (BotPluginInstallation, error) {
	row := q.db.QueryRowContext(ctx, updateBotPluginInstallationStatus,
		arg.Status,
		arg.Enabled,
		arg.BotID,
		arg.ID,
	)
	var i BotPluginInstallation
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.PluginID,
		&i.PluginName,
		&i.Version,
		&i.Status,
		&i.Enabled,
		&i.Config,
		&i.Metadata,
		&i.Manifest,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBotPluginResource = `-- name: UpsertBotPluginResource :one
INSERT INTO bot_plugin_resources (
  id, installation_id, resource_type, resource_key, resource_id, status, metadata
)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6
)
ON CONFLICT (installation_id, resource_type, resource_key)
DO UPDATE SET resource_id = EXCLUDED.resource_id,
              status = EXCLUDED.status,
              metadata = EXCLUDED.metadata,
              updated_at = CURRENT_TIMESTAMP
RETURNING id, installation_id, resource_type, resource_key, resource_id, status, metadata, created_at, updated_at
`

type UpsertBotPluginResourceParams struct {
	InstallationID string `json:"installation_id"`
	ResourceType   string `json:"resource_type"`
	ResourceKey    string `json:"resource_key"`
	ResourceID     string `json:"resource_id"`
	Status         string `json:"status"`
	Metadata       string `json:"metadata"`
}

func (q *Queries) UpsertBotPluginResource(ctx context.Context, arg UpsertBotPluginResourceParams) (BotPluginResource, error) {
	row := q.db.QueryRowContext(ctx, upsertBotPluginResource,
		arg.InstallationID,
		arg.ResourceType,
		arg.ResourceKey,
		arg.ResourceID,
		arg.Status,
		arg.Metadata,
	)
	var i BotPluginResource
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.ResourceType,
		&i.ResourceKey,
		&i.ResourceID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
