// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_oauth.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteProviderOAuthToken = `-- name: DeleteProviderOAuthToken :exec
DELETE FROM provider_oauth_tokens WHERE provider_id = ?1
`

func (q *Queries) DeleteProviderOAuthToken(ctx context.Context, providerID string) error {
	_, err := q.db.ExecContext(ctx, deleteProviderOAuthToken, providerID)
	return err
}

const getProviderOAuthTokenByProvider = `-- name: GetProviderOAuthTokenByProvider :one
SELECT id, provider_id, access_token, refresh_token, expires_at, scope, token_type, state, pkce_code_verifier, created_at, updated_at FROM provider_oauth_tokens WHERE provider_id = ?1
`

func (q *Queries) GetProviderOAuthTokenByProvider(ctx context.Context, providerID string) (ProviderOauthToken, error) {
	row := q.db.QueryRowContext(ctx, getProviderOAuthTokenByProvider, providerID)
	var i ProviderOauthToken
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scope,
		&i.TokenType,
		&i.State,
		&i.PkceCodeVerifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderOAuthTokenByState = `-- name: GetProviderOAuthTokenByState :one
SELECT id, provider_id, access_token, refresh_token, expires_at, scope, token_type, state, pkce_code_verifier, created_at, updated_at FROM provider_oauth_tokens WHERE state = ?1 AND state != ''
`

func (q *Queries) GetProviderOAuthTokenByState(ctx context.Context, state string) (ProviderOauthToken, error) {
	row := q.db.QueryRowContext(ctx, getProviderOAuthTokenByState, state)
	var i ProviderOauthToken
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scope,
		&i.TokenType,
		&i.State,
		&i.PkceCodeVerifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProviderOAuthState = `-- name: UpdateProviderOAuthState :exec
INSERT INTO provider_oauth_tokens (id, provider_id, state, pkce_code_verifier)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3
)
ON CONFLICT (provider_id) DO UPDATE SET
  state = EXCLUDED.state,
  pkce_code_verifier = EXCLUDED.pkce_code_verifier,
  updated_at = CURRENT_TIMESTAMP
`

type UpdateProviderOAuthStateParams struct {
	ProviderID       string `json:"provider_id"`
	State            string `json:"state"`
	PkceCodeVerifier string `json:"pkce_code_verifier"`
}

func (q *Queries) UpdateProviderOAuthState(ctx context.Context, arg UpdateProviderOAuthStateParams) error {
	_, err := q.db.ExecContext(ctx, updateProviderOAuthState, arg.ProviderID, arg.State, arg.PkceCodeVerifier)
	return err
}

const upsertProviderOAuthToken = `-- name: UpsertProviderOAuthToken :one
INSERT INTO provider_oauth_tokens (id, provider_id, access_token, refresh_token, expires_at, scope, token_type, state, pkce_code_verifier)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
)
ON CONFLICT (provider_id) DO UPDATE SET
  access_token = EXCLUDED.access_token,
  refresh_token = EXCLUDED.refresh_token,
  expires_at = EXCLUDED.expires_at,
  scope = EXCLUDED.scope,
  token_type = EXCLUDED.token_type,
  state = EXCLUDED.state,
  pkce_code_verifier = EXCLUDED.pkce_code_verifier,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, provider_id, access_token, refresh_token, expires_at, scope, token_type, state, pkce_code_verifier, created_at, updated_at
`

type UpsertProviderOAuthTokenParams struct {
	ProviderID       string         `json:"provider_id"`
	AccessToken      string         `json:"access_token"`
	RefreshToken     string         `json:"refresh_token"`
	ExpiresAt        sql.NullString `json:"expires_at"`
	Scope            string         `json:"scope"`
	TokenType        string         `json:"token_type"`
	State            string         `json:"state"`
	PkceCodeVerifier string         `json:"pkce_code_verifier"`
}

func (q *Queries) UpsertProviderOAuthToken(ctx context.Context, arg UpsertProviderOAuthTokenParams) (ProviderOauthToken, error) {
	row := q.db.QueryRowContext(ctx, upsertProviderOAuthToken,
		arg.ProviderID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.Scope,
		arg.TokenType,
		arg.State,
		arg.PkceCodeVerifier,
	)
	var i ProviderOauthToken
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scope,
		&i.TokenType,
		&i.State,
		&i.PkceCodeVerifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
