// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_logs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const completeScheduleLog = `-- name: CompleteScheduleLog :one
UPDATE schedule_logs
SET status = ?1,
    result_text = ?2,
    error_message = ?3,
    usage = ?4,
    model_id = ?5,
    completed_at = CURRENT_TIMESTAMP
WHERE id = ?6
RETURNING id, schedule_id, bot_id, session_id, status, result_text, error_message, usage, model_id, started_at, completed_at
`

type CompleteScheduleLogParams struct {
	Status       string         `json:"status"`
	ResultText   string         `json:"result_text"`
	ErrorMessage string         `json:"error_message"`
	Usage        sql.NullString `json:"usage"`
	ModelID      sql.NullString `json:"model_id"`
	ID           string         `json:"id"`
}

func (q *Queries) CompleteScheduleLog(ctx context.Context, arg CompleteScheduleLogParams) (ScheduleLog, error) {
	row := q.db.QueryRowContext(ctx, completeScheduleLog,
		arg.Status,
		arg.ResultText,
		arg.ErrorMessage,
		arg.Usage,
		arg.ModelID,
		arg.ID,
	)
	var i ScheduleLog
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.ResultText,
		&i.ErrorMessage,
		&i.Usage,
		&i.ModelID,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countScheduleLogsByBot = `-- name: CountScheduleLogsByBot :one
SELECT count(*) FROM schedule_logs WHERE bot_id = ?1
`

func (q *Queries) CountScheduleLogsByBot(ctx context.Context, botID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScheduleLogsByBot, botID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScheduleLogsBySchedule = `-- name: CountScheduleLogsBySchedule :one
SELECT count(*) FROM schedule_logs WHERE schedule_id = ?1
`

func (q *Queries) CountScheduleLogsBySchedule(ctx context.Context, scheduleID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScheduleLogsBySchedule, scheduleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createScheduleLog = `-- name: CreateScheduleLog :one
INSERT INTO schedule_logs (id, schedule_id, bot_id, session_id, started_at)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  CURRENT_TIMESTAMP
)
RETURNING id, schedule_id, bot_id, session_id, status, result_text, error_message, usage, started_at, completed_at
`

type CreateScheduleLogParams struct {
	ScheduleID string         `json:"schedule_id"`
	BotID      string         `json:"bot_id"`
	SessionID  sql.NullString `json:"session_id"`
}

type CreateScheduleLogRow struct {
	ID           string         `json:"id"`
	ScheduleID   string         `json:"schedule_id"`
	BotID        string         `json:"bot_id"`
	SessionID    sql.NullString `json:"session_id"`
	Status       string         `json:"status"`
	ResultText   string         `json:"result_text"`
	ErrorMessage string         `json:"error_message"`
	Usage        sql.NullString `json:"usage"`
	StartedAt    string         `json:"started_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
}

func (q *Queries) CreateScheduleLog(ctx context.Context, arg CreateScheduleLogParams) (CreateScheduleLogRow, error) {
	row := q.db.QueryRowContext(ctx, createScheduleLog, arg.ScheduleID, arg.BotID, arg.SessionID)
	var i CreateScheduleLogRow
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.BotID,
		&i.SessionID,
		&i.Status,
		&i.ResultText,
		&i.ErrorMessage,
		&i.Usage,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteScheduleLogsByBot = `-- name: DeleteScheduleLogsByBot :exec
DELETE FROM schedule_logs WHERE bot_id = ?1
`

func (q *Queries) DeleteScheduleLogsByBot(ctx context.Context, botID string) error {
	_, err := q.db.ExecContext(ctx, deleteScheduleLogsByBot, botID)
	return err
}

const deleteScheduleLogsBySchedule = `-- name: DeleteScheduleLogsBySchedule :exec
DELETE FROM schedule_logs WHERE schedule_id = ?1
`

func (q *Queries) DeleteScheduleLogsBySchedule(ctx context.Context, scheduleID string) error {
	_, err := q.db.ExecContext(ctx, deleteScheduleLogsBySchedule, scheduleID)
	return err
}

const listScheduleLogsByBot = `-- name: ListScheduleLogsByBot :many
SELECT id, schedule_id, bot_id, session_id, status, result_text, error_message, usage, started_at, completed_at
FROM schedule_logs
WHERE bot_id = ?1
ORDER BY started_at DESC
LIMIT ?3 OFFSET ?2
`

type ListScheduleLogsByBotParams struct {
	BotID string `json:"bot_id"`
	Off   int64  `json:"off"`
	Lim   int64  `json:"lim"`
}

type ListScheduleLogsByBotRow struct {
	ID           string         `json:"id"`
	ScheduleID   string         `json:"schedule_id"`
	BotID        string         `json:"bot_id"`
	SessionID    sql.NullString `json:"session_id"`
	Status       string         `json:"status"`
	ResultText   string         `json:"result_text"`
	ErrorMessage string         `json:"error_message"`
	Usage        sql.NullString `json:"usage"`
	StartedAt    string         `json:"started_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
}

func (q *Queries) ListScheduleLogsByBot(ctx context.Context, arg ListScheduleLogsByBotParams) ([]ListScheduleLogsByBotRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleLogsByBot, arg.BotID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleLogsByBotRow
	for rows.Next() {
		var i ListScheduleLogsByBotRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.BotID,
			&i.SessionID,
			&i.Status,
			&i.ResultText,
			&i.ErrorMessage,
			&i.Usage,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleLogsBySchedule = `-- name: ListScheduleLogsBySchedule :many
SELECT id, schedule_id, bot_id, session_id, status, result_text, error_message, usage, started_at, completed_at
FROM schedule_logs
WHERE schedule_id = ?1
ORDER BY started_at DESC
LIMIT ?3 OFFSET ?2
`

type ListScheduleLogsByScheduleParams struct {
	ScheduleID string `json:"schedule_id"`
	Off        int64  `json:"off"`
	Lim        int64  `json:"lim"`
}

type ListScheduleLogsByScheduleRow struct {
	ID           string         `json:"id"`
	ScheduleID   string         `json:"schedule_id"`
	BotID        string         `json:"bot_id"`
	SessionID    sql.NullString `json:"session_id"`
	Status       string         `json:"status"`
	ResultText   string         `json:"result_text"`
	ErrorMessage string         `json:"error_message"`
	Usage        sql.NullString `json:"usage"`
	StartedAt    string         `json:"started_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
}

func (q *Queries) ListScheduleLogsBySchedule(ctx context.Context, arg ListScheduleLogsByScheduleParams) ([]ListScheduleLogsByScheduleRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduleLogsBySchedule, arg.ScheduleID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleLogsByScheduleRow
	for rows.Next() {
		var i ListScheduleLogsByScheduleRow
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.BotID,
			&i.SessionID,
			&i.Status,
			&i.ResultText,
			&i.ErrorMessage,
			&i.Usage,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
