// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search_providers.sql

package sqlc

import (
	"context"
)

const createSearchProvider = `-- name: CreateSearchProvider :one
INSERT INTO search_providers (id, name, provider, config, enable)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4
)
RETURNING id, name, provider, config, enable, created_at, updated_at
`

type CreateSearchProviderParams struct {
	Name     string `json:"name"`
	Provider string `json:"provider"`
	Config   string `json:"config"`
	Enable   int64  `json:"enable"`
}

func (q *Queries) CreateSearchProvider(ctx context.Context, arg CreateSearchProviderParams) (SearchProvider, error) {
	row := q.db.QueryRowContext(ctx, createSearchProvider,
		arg.Name,
		arg.Provider,
		arg.Config,
		arg.Enable,
	)
	var i SearchProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.Enable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSearchProvider = `-- name: DeleteSearchProvider :exec
DELETE FROM search_providers WHERE id = ?1
`

func (q *Queries) DeleteSearchProvider(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSearchProvider, id)
	return err
}

const getSearchProviderByID = `-- name: GetSearchProviderByID :one
SELECT id, name, provider, config, enable, created_at, updated_at FROM search_providers WHERE id = ?1
`

func (q *Queries) GetSearchProviderByID(ctx context.Context, id string) (SearchProvider, error) {
	row := q.db.QueryRowContext(ctx, getSearchProviderByID, id)
	var i SearchProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.Enable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSearchProviderByName = `-- name: GetSearchProviderByName :one
SELECT id, name, provider, config, enable, created_at, updated_at FROM search_providers WHERE name = ?1
`

func (q *Queries) GetSearchProviderByName(ctx context.Context, name string) (SearchProvider, error) {
	row := q.db.QueryRowContext(ctx, getSearchProviderByName, name)
	var i SearchProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.Enable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSearchProviders = `-- name: ListSearchProviders :many
SELECT id, name, provider, config, enable, created_at, updated_at FROM search_providers
ORDER BY created_at DESC
`

func (q *Queries) ListSearchProviders(ctx context.Context) ([]SearchProvider, error) {
	rows, err := q.db.QueryContext(ctx, listSearchProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProvider
	for rows.Next() {
		var i SearchProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Config,
			&i.Enable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearchProvidersByProvider = `-- name: ListSearchProvidersByProvider :many
SELECT id, name, provider, config, enable, created_at, updated_at FROM search_providers
WHERE provider = ?1
ORDER BY created_at DESC
`

func (q *Queries) ListSearchProvidersByProvider(ctx context.Context, provider string) ([]SearchProvider, error) {
	rows, err := q.db.QueryContext(ctx, listSearchProvidersByProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProvider
	for rows.Next() {
		var i SearchProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Config,
			&i.Enable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSearchProvider = `-- name: UpdateSearchProvider :one
UPDATE search_providers
SET
  name = ?1,
  provider = ?2,
  config = ?3,
  enable = ?4,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?5
RETURNING id, name, provider, config, enable, created_at, updated_at
`

type UpdateSearchProviderParams struct {
	Name     string `json:"name"`
	Provider string `json:"provider"`
	Config   string `json:"config"`
	Enable   int64  `json:"enable"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateSearchProvider(ctx context.Context, arg UpdateSearchProviderParams) (SearchProvider, error) {
	row := q.db.QueryRowContext(ctx, updateSearchProvider,
		arg.Name,
		arg.Provider,
		arg.Config,
		arg.Enable,
		arg.ID,
	)
	var i SearchProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.Enable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
