// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_events.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countSessionEvents = `-- name: CountSessionEvents :one
SELECT COUNT(*) FROM bot_session_events
WHERE session_id = ?1
`

func (q *Queries) CountSessionEvents(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionEvents, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSessionEvent = `-- name: CreateSessionEvent :one
INSERT INTO bot_session_events (id, bot_id, session_id, event_kind, event_data, external_message_id, sender_channel_identity_id, received_at_ms)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7
)
ON CONFLICT DO NOTHING
RETURNING id
`

type CreateSessionEventParams struct {
	BotID                   string         `json:"bot_id"`
	SessionID               string         `json:"session_id"`
	EventKind               string         `json:"event_kind"`
	EventData               string         `json:"event_data"`
	ExternalMessageID       sql.NullString `json:"external_message_id"`
	SenderChannelIdentityID sql.NullString `json:"sender_channel_identity_id"`
	ReceivedAtMs            int64          `json:"received_at_ms"`
}

func (q *Queries) CreateSessionEvent(ctx context.Context, arg CreateSessionEventParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createSessionEvent,
		arg.BotID,
		arg.SessionID,
		arg.EventKind,
		arg.EventData,
		arg.ExternalMessageID,
		arg.SenderChannelIdentityID,
		arg.ReceivedAtMs,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listSessionEventsBySession = `-- name: ListSessionEventsBySession :many
SELECT id, bot_id, session_id, event_kind, event_data, external_message_id, sender_channel_identity_id, received_at_ms, created_at FROM bot_session_events
WHERE session_id = ?1
ORDER BY received_at_ms ASC
`

func (q *Queries) ListSessionEventsBySession(ctx context.Context, sessionID string) ([]BotSessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSessionEventsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSessionEvent
	for rows.Next() {
		var i BotSessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.EventKind,
			&i.EventData,
			&i.ExternalMessageID,
			&i.SenderChannelIdentityID,
			&i.ReceivedAtMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEventsBySessionAfter = `-- name: ListSessionEventsBySessionAfter :many
SELECT id, bot_id, session_id, event_kind, event_data, external_message_id, sender_channel_identity_id, received_at_ms, created_at FROM bot_session_events
WHERE session_id = ?1 AND received_at_ms >= ?2
ORDER BY received_at_ms ASC
`

type ListSessionEventsBySessionAfterParams struct {
	SessionID    string `json:"session_id"`
	ReceivedAtMs int64  `json:"received_at_ms"`
}

func (q *Queries) ListSessionEventsBySessionAfter(ctx context.Context, arg ListSessionEventsBySessionAfterParams) ([]BotSessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSessionEventsBySessionAfter, arg.SessionID, arg.ReceivedAtMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSessionEvent
	for rows.Next() {
		var i BotSessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.EventKind,
			&i.EventData,
			&i.ExternalMessageID,
			&i.SenderChannelIdentityID,
			&i.ReceivedAtMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
