// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteSettingsByBotID = `-- name: DeleteSettingsByBotID :exec
UPDATE bots
SET language = 'auto',
    command_ui_language = 'auto',
    reasoning_enabled = false,
    reasoning_effort = 'medium',
    heartbeat_enabled = false,
    heartbeat_interval = 1440,
    heartbeat_prompt = '',
    compaction_enabled = false,
    compaction_threshold = 100000,
    compaction_ratio = 80,
    chat_model_id = NULL,
    heartbeat_model_id = NULL,
    compaction_model_id = NULL,
    title_model_id = NULL,
    image_model_id = NULL,
    search_provider_id = NULL,
    fetch_provider_id = NULL,
    memory_provider_id = NULL,
    tts_model_id = NULL,
    transcription_model_id = NULL,
    persist_full_tool_results = false,
    show_tool_calls_in_im = false,
    tool_approval_config = '{"enabled":false,"read":{"require_approval":false,"bypass_globs":[],"force_review_globs":[]},"write":{"require_approval":true,"bypass_globs":["/data/**","/tmp/**"],"force_review_globs":[]},"exec":{"require_approval":false,"bypass_commands":[],"force_review_commands":[]}}',
    display_enabled = false,
    overlay_provider = '',
    overlay_enabled = false,
    overlay_config = '{}',
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
`

func (q *Queries) DeleteSettingsByBotID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSettingsByBotID, id)
	return err
}

const getSettingsByBotID = `-- name: GetSettingsByBotID :one
SELECT
  bots.id AS bot_id,
  bots.language,
  bots.reasoning_enabled,
  bots.reasoning_effort,
  bots.heartbeat_enabled,
  bots.heartbeat_interval,
  bots.heartbeat_prompt,
  bots.compaction_enabled,
  bots.compaction_threshold,
  bots.compaction_ratio,
  bots.timezone,
  chat_models.id AS chat_model_id,
  heartbeat_models.id AS heartbeat_model_id,
  compaction_models.id AS compaction_model_id,
  title_models.id AS title_model_id,
  search_providers.id AS search_provider_id,
  fetch_providers.id AS fetch_provider_id,
  memory_providers.id AS memory_provider_id,
  image_models.id AS image_model_id,
  tts_models.id AS tts_model_id,
  transcription_models.id AS transcription_model_id,
  bots.persist_full_tool_results,
  bots.show_tool_calls_in_im,
  bots.tool_approval_config,
  bots.display_enabled,
  bots.overlay_provider,
  bots.overlay_enabled,
  bots.overlay_config,
  bots.command_ui_language
FROM bots
LEFT JOIN models AS chat_models ON chat_models.id = bots.chat_model_id
LEFT JOIN models AS heartbeat_models ON heartbeat_models.id = bots.heartbeat_model_id
LEFT JOIN models AS compaction_models ON compaction_models.id = bots.compaction_model_id
LEFT JOIN models AS title_models ON title_models.id = bots.title_model_id
LEFT JOIN models AS image_models ON image_models.id = bots.image_model_id
LEFT JOIN search_providers ON search_providers.id = bots.search_provider_id
LEFT JOIN fetch_providers ON fetch_providers.id = bots.fetch_provider_id
LEFT JOIN memory_providers ON memory_providers.id = bots.memory_provider_id
LEFT JOIN models AS tts_models ON tts_models.id = bots.tts_model_id
LEFT JOIN models AS transcription_models ON transcription_models.id = bots.transcription_model_id
WHERE bots.id = ?1
`

type GetSettingsByBotIDRow struct {
	BotID                  string         `json:"bot_id"`
	Language               string         `json:"language"`
	ReasoningEnabled       int64          `json:"reasoning_enabled"`
	ReasoningEffort        string         `json:"reasoning_effort"`
	HeartbeatEnabled       int64          `json:"heartbeat_enabled"`
	HeartbeatInterval      int64          `json:"heartbeat_interval"`
	HeartbeatPrompt        string         `json:"heartbeat_prompt"`
	CompactionEnabled      int64          `json:"compaction_enabled"`
	CompactionThreshold    int64          `json:"compaction_threshold"`
	CompactionRatio        int64          `json:"compaction_ratio"`
	Timezone               sql.NullString `json:"timezone"`
	ChatModelID            sql.NullString `json:"chat_model_id"`
	HeartbeatModelID       sql.NullString `json:"heartbeat_model_id"`
	CompactionModelID      sql.NullString `json:"compaction_model_id"`
	TitleModelID           sql.NullString `json:"title_model_id"`
	SearchProviderID       sql.NullString `json:"search_provider_id"`
	FetchProviderID        sql.NullString `json:"fetch_provider_id"`
	MemoryProviderID       sql.NullString `json:"memory_provider_id"`
	ImageModelID           sql.NullString `json:"image_model_id"`
	TtsModelID             sql.NullString `json:"tts_model_id"`
	TranscriptionModelID   sql.NullString `json:"transcription_model_id"`
	PersistFullToolResults int64          `json:"persist_full_tool_results"`
	ShowToolCallsInIm      int64          `json:"show_tool_calls_in_im"`
	ToolApprovalConfig     string         `json:"tool_approval_config"`
	DisplayEnabled         int64          `json:"display_enabled"`
	OverlayProvider        string         `json:"overlay_provider"`
	OverlayEnabled         int64          `json:"overlay_enabled"`
	OverlayConfig          string         `json:"overlay_config"`
	CommandUiLanguage      string         `json:"command_ui_language"`
}

func (q *Queries) GetSettingsByBotID(ctx context.Context, id string) (GetSettingsByBotIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSettingsByBotID, id)
	var i GetSettingsByBotIDRow
	err := row.Scan(
		&i.BotID,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionRatio,
		&i.Timezone,
		&i.ChatModelID,
		&i.HeartbeatModelID,
		&i.CompactionModelID,
		&i.TitleModelID,
		&i.SearchProviderID,
		&i.FetchProviderID,
		&i.MemoryProviderID,
		&i.ImageModelID,
		&i.TtsModelID,
		&i.TranscriptionModelID,
		&i.PersistFullToolResults,
		&i.ShowToolCallsInIm,
		&i.ToolApprovalConfig,
		&i.DisplayEnabled,
		&i.OverlayProvider,
		&i.OverlayEnabled,
		&i.OverlayConfig,
		&i.CommandUiLanguage,
	)
	return i, err
}

const upsertBotSettings = `-- name: UpsertBotSettings :one
UPDATE bots
SET language = ?1,
    reasoning_enabled = ?2,
    reasoning_effort = ?3,
    heartbeat_enabled = ?4,
    heartbeat_interval = ?5,
    heartbeat_prompt = ?6,
    compaction_enabled = ?7,
    compaction_threshold = ?8,
    compaction_ratio = ?9,
    timezone = COALESCE(?10, bots.timezone),
    chat_model_id = COALESCE(?11, bots.chat_model_id),
    heartbeat_model_id = COALESCE(?12, bots.heartbeat_model_id),
    compaction_model_id = COALESCE(?13, bots.compaction_model_id),
    title_model_id = COALESCE(?14, bots.title_model_id),
    search_provider_id = COALESCE(?15, bots.search_provider_id),
    fetch_provider_id = CASE
      WHEN ?16 = 1 THEN ?17
      ELSE bots.fetch_provider_id
    END,
    memory_provider_id = COALESCE(?18, bots.memory_provider_id),
    image_model_id = COALESCE(?19, bots.image_model_id),
    tts_model_id = COALESCE(?20, bots.tts_model_id),
    transcription_model_id = COALESCE(?21, bots.transcription_model_id),
    persist_full_tool_results = ?22,
    show_tool_calls_in_im = ?23,
    tool_approval_config = ?24,
    display_enabled = ?25,
    overlay_provider = ?26,
    overlay_enabled = ?27,
    overlay_config = ?28,
    command_ui_language = ?29,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?30
RETURNING
  id AS bot_id,
  language,
  reasoning_enabled,
  reasoning_effort,
  heartbeat_enabled,
  heartbeat_interval,
  heartbeat_prompt,
  compaction_enabled,
  compaction_threshold,
  compaction_ratio,
  timezone,
  chat_model_id,
  heartbeat_model_id,
  compaction_model_id,
  title_model_id,
  search_provider_id,
  fetch_provider_id,
  memory_provider_id,
  image_model_id,
  tts_model_id,
  transcription_model_id,
  persist_full_tool_results,
  show_tool_calls_in_im,
  tool_approval_config,
  display_enabled,
  overlay_provider,
  overlay_enabled,
  overlay_config,
  command_ui_language
`

type UpsertBotSettingsParams struct {
	Language               string         `json:"language"`
	ReasoningEnabled       int64          `json:"reasoning_enabled"`
	ReasoningEffort        string         `json:"reasoning_effort"`
	HeartbeatEnabled       int64          `json:"heartbeat_enabled"`
	HeartbeatInterval      int64          `json:"heartbeat_interval"`
	HeartbeatPrompt        string         `json:"heartbeat_prompt"`
	CompactionEnabled      int64          `json:"compaction_enabled"`
	CompactionThreshold    int64          `json:"compaction_threshold"`
	CompactionRatio        int64          `json:"compaction_ratio"`
	Timezone               sql.NullString `json:"timezone"`
	ChatModelID            sql.NullString `json:"chat_model_id"`
	HeartbeatModelID       sql.NullString `json:"heartbeat_model_id"`
	CompactionModelID      sql.NullString `json:"compaction_model_id"`
	TitleModelID           sql.NullString `json:"title_model_id"`
	SearchProviderID       sql.NullString `json:"search_provider_id"`
	FetchProviderIDSet     interface{}    `json:"fetch_provider_id_set"`
	FetchProviderID        sql.NullString `json:"fetch_provider_id"`
	MemoryProviderID       sql.NullString `json:"memory_provider_id"`
	ImageModelID           sql.NullString `json:"image_model_id"`
	TtsModelID             sql.NullString `json:"tts_model_id"`
	TranscriptionModelID   sql.NullString `json:"transcription_model_id"`
	PersistFullToolResults int64          `json:"persist_full_tool_results"`
	ShowToolCallsInIm      int64          `json:"show_tool_calls_in_im"`
	ToolApprovalConfig     string         `json:"tool_approval_config"`
	DisplayEnabled         int64          `json:"display_enabled"`
	OverlayProvider        string         `json:"overlay_provider"`
	OverlayEnabled         int64          `json:"overlay_enabled"`
	OverlayConfig          string         `json:"overlay_config"`
	CommandUiLanguage      string         `json:"command_ui_language"`
	ID                     string         `json:"id"`
}

type UpsertBotSettingsRow struct {
	ID                     string         `json:"id"`
	Language               string         `json:"language"`
	ReasoningEnabled       int64          `json:"reasoning_enabled"`
	ReasoningEffort        string         `json:"reasoning_effort"`
	HeartbeatEnabled       int64          `json:"heartbeat_enabled"`
	HeartbeatInterval      int64          `json:"heartbeat_interval"`
	HeartbeatPrompt        string         `json:"heartbeat_prompt"`
	CompactionEnabled      int64          `json:"compaction_enabled"`
	CompactionThreshold    int64          `json:"compaction_threshold"`
	CompactionRatio        int64          `json:"compaction_ratio"`
	Timezone               sql.NullString `json:"timezone"`
	ChatModelID            sql.NullString `json:"chat_model_id"`
	HeartbeatModelID       sql.NullString `json:"heartbeat_model_id"`
	CompactionModelID      sql.NullString `json:"compaction_model_id"`
	TitleModelID           sql.NullString `json:"title_model_id"`
	SearchProviderID       sql.NullString `json:"search_provider_id"`
	FetchProviderID        sql.NullString `json:"fetch_provider_id"`
	MemoryProviderID       sql.NullString `json:"memory_provider_id"`
	ImageModelID           sql.NullString `json:"image_model_id"`
	TtsModelID             sql.NullString `json:"tts_model_id"`
	TranscriptionModelID   sql.NullString `json:"transcription_model_id"`
	PersistFullToolResults int64          `json:"persist_full_tool_results"`
	ShowToolCallsInIm      int64          `json:"show_tool_calls_in_im"`
	ToolApprovalConfig     string         `json:"tool_approval_config"`
	DisplayEnabled         int64          `json:"display_enabled"`
	OverlayProvider        string         `json:"overlay_provider"`
	OverlayEnabled         int64          `json:"overlay_enabled"`
	OverlayConfig          string         `json:"overlay_config"`
	CommandUiLanguage      string         `json:"command_ui_language"`
}

func (q *Queries) UpsertBotSettings(ctx context.Context, arg UpsertBotSettingsParams) (UpsertBotSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, upsertBotSettings,
		arg.Language,
		arg.ReasoningEnabled,
		arg.ReasoningEffort,
		arg.HeartbeatEnabled,
		arg.HeartbeatInterval,
		arg.HeartbeatPrompt,
		arg.CompactionEnabled,
		arg.CompactionThreshold,
		arg.CompactionRatio,
		arg.Timezone,
		arg.ChatModelID,
		arg.HeartbeatModelID,
		arg.CompactionModelID,
		arg.TitleModelID,
		arg.SearchProviderID,
		arg.FetchProviderIDSet,
		arg.FetchProviderID,
		arg.MemoryProviderID,
		arg.ImageModelID,
		arg.TtsModelID,
		arg.TranscriptionModelID,
		arg.PersistFullToolResults,
		arg.ShowToolCallsInIm,
		arg.ToolApprovalConfig,
		arg.DisplayEnabled,
		arg.OverlayProvider,
		arg.OverlayEnabled,
		arg.OverlayConfig,
		arg.CommandUiLanguage,
		arg.ID,
	)
	var i UpsertBotSettingsRow
	err := row.Scan(
		&i.ID,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionRatio,
		&i.Timezone,
		&i.ChatModelID,
		&i.HeartbeatModelID,
		&i.CompactionModelID,
		&i.TitleModelID,
		&i.SearchProviderID,
		&i.FetchProviderID,
		&i.MemoryProviderID,
		&i.ImageModelID,
		&i.TtsModelID,
		&i.TranscriptionModelID,
		&i.PersistFullToolResults,
		&i.ShowToolCallsInIm,
		&i.ToolApprovalConfig,
		&i.DisplayEnabled,
		&i.OverlayProvider,
		&i.OverlayEnabled,
		&i.OverlayConfig,
		&i.CommandUiLanguage,
	)
	return i, err
}
