// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token_usage.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countTokenUsageRecords = `-- name: CountTokenUsageRecords :one
SELECT COUNT(*) AS total
FROM bot_history_messages m
LEFT JOIN bot_sessions s ON s.id = m.session_id
LEFT JOIN bot_sessions ps ON ps.id = s.parent_session_id
WHERE m.bot_id = ?1
  AND m.usage IS NOT NULL
  AND json_valid(m.usage)
  AND datetime(m.created_at) >= datetime(?2)
  AND datetime(m.created_at) < datetime(?3)
  AND (?4 IS NULL OR m.model_id = ?4)
  AND (
    ?5 IS NULL
    OR COALESCE(
      CASE WHEN s.type = 'subagent' THEN COALESCE(ps.type, 'chat') ELSE s.type END,
      'chat'
    ) = ?5
  )
`

type CountTokenUsageRecordsParams struct {
	BotID       string      `json:"bot_id"`
	FromTime    interface{} `json:"from_time"`
	ToTime      interface{} `json:"to_time"`
	ModelID     interface{} `json:"model_id"`
	SessionType interface{} `json:"session_type"`
}

func (q *Queries) CountTokenUsageRecords(ctx context.Context, arg CountTokenUsageRecordsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTokenUsageRecords,
		arg.BotID,
		arg.FromTime,
		arg.ToTime,
		arg.ModelID,
		arg.SessionType,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getTokenUsageByDayAndType = `-- name: GetTokenUsageByDayAndType :many
SELECT
  COALESCE(
    CASE WHEN s.type = 'subagent' THEN COALESCE(ps.type, 'chat') ELSE s.type END,
    'chat'
  ) AS session_type,
  date(datetime(m.created_at)) AS day,
  COALESCE(SUM(CAST(json_extract(m.usage, '$.inputTokens') AS INTEGER)), 0) AS input_tokens,
  COALESCE(SUM(CAST(json_extract(m.usage, '$.outputTokens') AS INTEGER)), 0) AS output_tokens,
  COALESCE(SUM(CAST(json_extract(m.usage, '$.inputTokenDetails.cacheReadTokens') AS INTEGER)), 0) AS cache_read_tokens,
  COALESCE(SUM(CAST(json_extract(m.usage, '$.outputTokenDetails.reasoningTokens') AS INTEGER)), 0) AS reasoning_tokens
FROM bot_history_messages m
LEFT JOIN bot_sessions s ON s.id = m.session_id
LEFT JOIN bot_sessions ps ON ps.id = s.parent_session_id
WHERE m.bot_id = ?1
  AND m.usage IS NOT NULL
  AND json_valid(m.usage)
  AND datetime(m.created_at) >= datetime(?2)
  AND datetime(m.created_at) < datetime(?3)
  AND (?4 IS NULL OR m.model_id = ?4)
GROUP BY session_type, day
ORDER BY day, session_type
`

type GetTokenUsageByDayAndTypeParams struct {
	BotID    string      `json:"bot_id"`
	FromTime interface{} `json:"from_time"`
	ToTime   interface{} `json:"to_time"`
	ModelID  interface{} `json:"model_id"`
}

type GetTokenUsageByDayAndTypeRow struct {
	SessionType     interface{} `json:"session_type"`
	Day             interface{} `json:"day"`
	InputTokens     interface{} `json:"input_tokens"`
	OutputTokens    interface{} `json:"output_tokens"`
	CacheReadTokens interface{} `json:"cache_read_tokens"`
	ReasoningTokens interface{} `json:"reasoning_tokens"`
}

func (q *Queries) GetTokenUsageByDayAndType(ctx context.Context, arg GetTokenUsageByDayAndTypeParams) ([]GetTokenUsageByDayAndTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getTokenUsageByDayAndType,
		arg.BotID,
		arg.FromTime,
		arg.ToTime,
		arg.ModelID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTokenUsageByDayAndTypeRow
	for rows.Next() {
		var i GetTokenUsageByDayAndTypeRow
		if err := rows.Scan(
			&i.SessionType,
			&i.Day,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.ReasoningTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTokenUsageByModel = `-- name: GetTokenUsageByModel :many
SELECT
  m.model_id,
  COALESCE(mo.model_id, 'unknown') AS model_slug,
  COALESCE(mo.name, 'Unknown') AS model_name,
  COALESCE(lp.name, 'Unknown') AS provider_name,
  COALESCE(SUM(CAST(json_extract(m.usage, '$.inputTokens') AS INTEGER)), 0) AS input_tokens,
  COALESCE(SUM(CAST(json_extract(m.usage, '$.outputTokens') AS INTEGER)), 0) AS output_tokens
FROM bot_history_messages m
LEFT JOIN models mo ON mo.id = m.model_id
LEFT JOIN providers lp ON lp.id = mo.provider_id
WHERE m.bot_id = ?1
  AND m.usage IS NOT NULL
  AND json_valid(m.usage)
  AND datetime(m.created_at) >= datetime(?2)
  AND datetime(m.created_at) < datetime(?3)
GROUP BY m.model_id, mo.model_id, mo.name, lp.name
ORDER BY input_tokens DESC
`

type GetTokenUsageByModelParams struct {
	BotID    string      `json:"bot_id"`
	FromTime interface{} `json:"from_time"`
	ToTime   interface{} `json:"to_time"`
}

type GetTokenUsageByModelRow struct {
	ModelID      sql.NullString `json:"model_id"`
	ModelSlug    string         `json:"model_slug"`
	ModelName    string         `json:"model_name"`
	ProviderName string         `json:"provider_name"`
	InputTokens  interface{}    `json:"input_tokens"`
	OutputTokens interface{}    `json:"output_tokens"`
}

func (q *Queries) GetTokenUsageByModel(ctx context.Context, arg GetTokenUsageByModelParams) ([]GetTokenUsageByModelRow, error) {
	rows, err := q.db.QueryContext(ctx, getTokenUsageByModel, arg.BotID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTokenUsageByModelRow
	for rows.Next() {
		var i GetTokenUsageByModelRow
		if err := rows.Scan(
			&i.ModelID,
			&i.ModelSlug,
			&i.ModelName,
			&i.ProviderName,
			&i.InputTokens,
			&i.OutputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenUsageRecords = `-- name: ListTokenUsageRecords :many
SELECT
  m.id,
  m.created_at,
  m.session_id,
  COALESCE(
    CASE WHEN s.type = 'subagent' THEN COALESCE(ps.type, 'chat') ELSE s.type END,
    'chat'
  ) AS session_type,
  m.model_id,
  COALESCE(mo.model_id, 'unknown') AS model_slug,
  COALESCE(mo.name, 'Unknown') AS model_name,
  COALESCE(lp.name, 'Unknown') AS provider_name,
  COALESCE(CAST(json_extract(m.usage, '$.inputTokens') AS INTEGER), 0) AS input_tokens,
  COALESCE(CAST(json_extract(m.usage, '$.outputTokens') AS INTEGER), 0) AS output_tokens,
  COALESCE(CAST(json_extract(m.usage, '$.inputTokenDetails.cacheReadTokens') AS INTEGER), 0) AS cache_read_tokens,
  COALESCE(CAST(json_extract(m.usage, '$.outputTokenDetails.reasoningTokens') AS INTEGER), 0) AS reasoning_tokens
FROM bot_history_messages m
LEFT JOIN bot_sessions s ON s.id = m.session_id
LEFT JOIN bot_sessions ps ON ps.id = s.parent_session_id
LEFT JOIN models mo ON mo.id = m.model_id
LEFT JOIN providers lp ON lp.id = mo.provider_id
WHERE m.bot_id = ?1
  AND m.usage IS NOT NULL
  AND json_valid(m.usage)
  AND datetime(m.created_at) >= datetime(?2)
  AND datetime(m.created_at) < datetime(?3)
  AND (?4 IS NULL OR m.model_id = ?4)
  AND (
    ?5 IS NULL
    OR COALESCE(
      CASE WHEN s.type = 'subagent' THEN COALESCE(ps.type, 'chat') ELSE s.type END,
      'chat'
    ) = ?5
  )
ORDER BY m.created_at DESC, m.id DESC
LIMIT ?7
OFFSET ?6
`

type ListTokenUsageRecordsParams struct {
	BotID       string      `json:"bot_id"`
	FromTime    interface{} `json:"from_time"`
	ToTime      interface{} `json:"to_time"`
	ModelID     interface{} `json:"model_id"`
	SessionType interface{} `json:"session_type"`
	PageOffset  int64       `json:"page_offset"`
	PageLimit   int64       `json:"page_limit"`
}

type ListTokenUsageRecordsRow struct {
	ID              string         `json:"id"`
	CreatedAt       string         `json:"created_at"`
	SessionID       sql.NullString `json:"session_id"`
	SessionType     interface{}    `json:"session_type"`
	ModelID         sql.NullString `json:"model_id"`
	ModelSlug       string         `json:"model_slug"`
	ModelName       string         `json:"model_name"`
	ProviderName    string         `json:"provider_name"`
	InputTokens     interface{}    `json:"input_tokens"`
	OutputTokens    interface{}    `json:"output_tokens"`
	CacheReadTokens interface{}    `json:"cache_read_tokens"`
	ReasoningTokens interface{}    `json:"reasoning_tokens"`
}

func (q *Queries) ListTokenUsageRecords(ctx context.Context, arg ListTokenUsageRecordsParams) ([]ListTokenUsageRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTokenUsageRecords,
		arg.BotID,
		arg.FromTime,
		arg.ToTime,
		arg.ModelID,
		arg.SessionType,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTokenUsageRecordsRow
	for rows.Next() {
		var i ListTokenUsageRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.SessionID,
			&i.SessionType,
			&i.ModelID,
			&i.ModelSlug,
			&i.ModelName,
			&i.ProviderName,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.ReasoningTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
