// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countAccounts = `-- name: CountAccounts :one
SELECT COUNT(*) AS count
FROM users
WHERE username IS NOT NULL
  AND password_hash IS NOT NULL
`

func (q *Queries) CountAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccounts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
UPDATE users
SET username = ?1,
    email = ?2,
    password_hash = ?3,
    role = ?4,
    display_name = ?5,
    avatar_url = ?6,
    is_active = ?7,
    data_root = ?8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?9
RETURNING id, username, email, password_hash, role, display_name, avatar_url, timezone, data_root, last_login_at, is_active, metadata, created_at, updated_at
`

type CreateAccountParams struct {
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	Role         string         `json:"role"`
	DisplayName  sql.NullString `json:"display_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	IsActive     int64          `json:"is_active"`
	DataRoot     sql.NullString `json:"data_root"`
	UserID       string         `json:"user_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.IsActive,
		arg.DataRoot,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.DataRoot,
		&i.LastLoginAt,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, is_active, metadata)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2
)
RETURNING id, username, email, password_hash, role, display_name, avatar_url, timezone, data_root, last_login_at, is_active, metadata, created_at, updated_at
`

type CreateUserParams struct {
	IsActive int64  `json:"is_active"`
	Metadata string `json:"metadata"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.IsActive, arg.Metadata)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.DataRoot,
		&i.LastLoginAt,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByIdentity = `-- name: GetAccountByIdentity :one
SELECT id, username, email, password_hash, role, display_name, avatar_url, timezone, data_root, last_login_at, is_active, metadata, created_at, updated_at FROM users WHERE username = ?1 OR email = ?1
`

func (q *Queries) GetAccountByIdentity(ctx context.Context, identity sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getAccountByIdentity, identity)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.DataRoot,
		&i.LastLoginAt,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUserID = `-- name: GetAccountByUserID :one
SELECT id, username, email, password_hash, role, display_name, avatar_url, timezone, data_root, last_login_at, is_active, metadata, created_at, updated_at FROM users WHERE id = ?1
`

func (q *Queries) GetAccountByUserID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getAccountByUserID, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.DataRoot,
		&i.LastLoginAt,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, role, display_name, avatar_url, timezone, data_root, last_login_at, is_active, metadata, created_at, updated_at
FROM users
WHERE id = ?1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.DataRoot,
		&i.LastLoginAt,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, username, email, password_hash, role, display_name, avatar_url, timezone, data_root, last_login_at, is_active, metadata, created_at, updated_at FROM users
WHERE username IS NOT NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAccounts(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Timezone,
			&i.DataRoot,
			&i.LastLoginAt,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :one
UPDATE users
SET username = NULL,
    email = NULL,
    password_hash = NULL,
    display_name = NULL,
    avatar_url = NULL,
    data_root = NULL,
    is_active = 0,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
RETURNING id
`

func (q *Queries) RemoveMember(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRowContext(ctx, removeMember, userID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const searchAccounts = `-- name: SearchAccounts :many
SELECT id, username, email, password_hash, role, display_name, avatar_url, timezone, data_root, last_login_at, is_active, metadata, created_at, updated_at
FROM users
WHERE username IS NOT NULL
  AND (
    ?1 = ''
    OR lower(username) LIKE '%' || lower(?1) || '%'
    OR lower(COALESCE(display_name, '')) LIKE '%' || lower(?1) || '%'
    OR lower(COALESCE(email, '')) LIKE '%' || lower(?1) || '%'
  )
ORDER BY last_login_at DESC, created_at DESC
LIMIT ?2
`

type SearchAccountsParams struct {
	Query      interface{} `json:"query"`
	LimitCount int64       `json:"limit_count"`
}

func (q *Queries) SearchAccounts(ctx context.Context, arg SearchAccountsParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchAccounts, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Timezone,
			&i.DataRoot,
			&i.LastLoginAt,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountAdmin = `-- name: UpdateAccountAdmin :one
UPDATE users
SET role = ?1,
    display_name = ?2,
    avatar_url = ?3,
    is_active = ?4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?5
RETURNING id, username, email, password_hash, role, display_name, avatar_url, timezone, data_root, last_login_at, is_active, metadata, created_at, updated_at
`

type UpdateAccountAdminParams struct {
	Role        string         `json:"role"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	IsActive    int64          `json:"is_active"`
	UserID      string         `json:"user_id"`
}

func (q *Queries) UpdateAccountAdmin(ctx context.Context, arg UpdateAccountAdminParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateAccountAdmin,
		arg.Role,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.IsActive,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.DataRoot,
		&i.LastLoginAt,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountLastLogin = `-- name: UpdateAccountLastLogin :one
UPDATE users
SET last_login_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
RETURNING id, username, email, password_hash, role, display_name, avatar_url, timezone, data_root, last_login_at, is_active, metadata, created_at, updated_at
`

func (q *Queries) UpdateAccountLastLogin(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, updateAccountLastLogin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.DataRoot,
		&i.LastLoginAt,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountPassword = `-- name: UpdateAccountPassword :one
UPDATE users
SET password_hash = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
RETURNING id, username, email, password_hash, role, display_name, avatar_url, timezone, data_root, last_login_at, is_active, metadata, created_at, updated_at
`

type UpdateAccountPasswordParams struct {
	PasswordHash sql.NullString `json:"password_hash"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateAccountPassword, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.DataRoot,
		&i.LastLoginAt,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountProfile = `-- name: UpdateAccountProfile :one
UPDATE users
SET display_name = ?1,
    avatar_url = ?2,
    timezone = ?3,
    is_active = ?4,
    metadata = ?5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?6
RETURNING id, username, email, password_hash, role, display_name, avatar_url, timezone, data_root, last_login_at, is_active, metadata, created_at, updated_at
`

type UpdateAccountProfileParams struct {
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	Timezone    string         `json:"timezone"`
	IsActive    int64          `json:"is_active"`
	Metadata    string         `json:"metadata"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateAccountProfile,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Timezone,
		arg.IsActive,
		arg.Metadata,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.DataRoot,
		&i.LastLoginAt,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAccountByUsername = `-- name: UpsertAccountByUsername :one
INSERT INTO users (id, username, email, password_hash, role, display_name, avatar_url, is_active, data_root, metadata)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  '{}'
)
ON CONFLICT (username) DO UPDATE SET
  email = EXCLUDED.email,
  password_hash = EXCLUDED.password_hash,
  role = EXCLUDED.role,
  display_name = EXCLUDED.display_name,
  avatar_url = EXCLUDED.avatar_url,
  is_active = EXCLUDED.is_active,
  data_root = EXCLUDED.data_root,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, username, email, password_hash, role, display_name, avatar_url, timezone, data_root, last_login_at, is_active, metadata, created_at, updated_at
`

type UpsertAccountByUsernameParams struct {
	UserID       string         `json:"user_id"`
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	Role         string         `json:"role"`
	DisplayName  sql.NullString `json:"display_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	IsActive     int64          `json:"is_active"`
	DataRoot     sql.NullString `json:"data_root"`
}

func (q *Queries) UpsertAccountByUsername(ctx context.Context, arg UpsertAccountByUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertAccountByUsername,
		arg.UserID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.IsActive,
		arg.DataRoot,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Timezone,
		&i.DataRoot,
		&i.LastLoginAt,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
