// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_input.sql

package sqlc

import (
	"context"
	"database/sql"
)

const cancelPendingUserInputsBySession = `-- name: CancelPendingUserInputsBySession :many
UPDATE user_input_requests
SET status = 'canceled',
    result_json = ?1,
    responded_at = CURRENT_TIMESTAMP,
    canceled_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE bot_id = ?2
  AND session_id = ?3
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at = '' OR julianday(expires_at) > julianday('now'))
RETURNING id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
`

type CancelPendingUserInputsBySessionParams struct {
	ResultJson string `json:"result_json"`
	BotID      string `json:"bot_id"`
	SessionID  string `json:"session_id"`
}

func (q *Queries) CancelPendingUserInputsBySession(ctx context.Context, arg CancelPendingUserInputsBySessionParams) ([]UserInputRequest, error) {
	rows, err := q.db.QueryContext(ctx, cancelPendingUserInputsBySession, arg.ResultJson, arg.BotID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInputRequest
	for rows.Next() {
		var i UserInputRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.ToolCallID,
			&i.ToolName,
			&i.ShortID,
			&i.Status,
			&i.InputJson,
			&i.UiPayloadJson,
			&i.ResultJson,
			&i.ProviderMetadata,
			&i.RequestedByChannelIdentityID,
			&i.RespondedByChannelIdentityID,
			&i.AssistantMessageID,
			&i.ToolResultMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.CanceledAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelUserInputRequest = `-- name: CancelUserInputRequest :one
UPDATE user_input_requests
SET status = 'canceled',
    result_json = ?1,
    responded_by_channel_identity_id = ?2,
    responded_at = CURRENT_TIMESTAMP,
    canceled_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?3
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at = '' OR julianday(expires_at) > julianday('now'))
RETURNING id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
`

type CancelUserInputRequestParams struct {
	ResultJson                   string         `json:"result_json"`
	RespondedByChannelIdentityID sql.NullString `json:"responded_by_channel_identity_id"`
	ID                           string         `json:"id"`
}

func (q *Queries) CancelUserInputRequest(ctx context.Context, arg CancelUserInputRequestParams) (UserInputRequest, error) {
	row := q.db.QueryRowContext(ctx, cancelUserInputRequest, arg.ResultJson, arg.RespondedByChannelIdentityID, arg.ID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserInputRequest = `-- name: CreateUserInputRequest :one
INSERT INTO user_input_requests (
  id,
  bot_id,
  session_id,
  route_id,
  channel_identity_id,
  tool_call_id,
  tool_name,
  short_id,
  input_json,
  ui_payload_json,
  provider_metadata,
  requested_by_channel_identity_id,
  source_platform,
  reply_target,
  conversation_type,
  expires_at
) VALUES (
  lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-' || '4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  (
    SELECT COALESCE(MAX(short_id), 0) + 1
    FROM user_input_requests
    WHERE session_id = ?2
  ),
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13,
  ?14
)
ON CONFLICT (session_id, tool_call_id) DO UPDATE
SET input_json = EXCLUDED.input_json,
    ui_payload_json = EXCLUDED.ui_payload_json,
    provider_metadata = EXCLUDED.provider_metadata,
    requested_by_channel_identity_id = EXCLUDED.requested_by_channel_identity_id,
    source_platform = EXCLUDED.source_platform,
    reply_target = EXCLUDED.reply_target,
    conversation_type = EXCLUDED.conversation_type,
    expires_at = EXCLUDED.expires_at,
    updated_at = CURRENT_TIMESTAMP
WHERE user_input_requests.status = 'pending'
  AND (user_input_requests.expires_at IS NULL OR user_input_requests.expires_at = '' OR julianday(user_input_requests.expires_at) > julianday('now'))
RETURNING id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
`

type CreateUserInputRequestParams struct {
	BotID                        string         `json:"bot_id"`
	SessionID                    string         `json:"session_id"`
	RouteID                      sql.NullString `json:"route_id"`
	ChannelIdentityID            sql.NullString `json:"channel_identity_id"`
	ToolCallID                   string         `json:"tool_call_id"`
	ToolName                     string         `json:"tool_name"`
	InputJson                    string         `json:"input_json"`
	UiPayloadJson                string         `json:"ui_payload_json"`
	ProviderMetadata             string         `json:"provider_metadata"`
	RequestedByChannelIdentityID sql.NullString `json:"requested_by_channel_identity_id"`
	SourcePlatform               string         `json:"source_platform"`
	ReplyTarget                  string         `json:"reply_target"`
	ConversationType             string         `json:"conversation_type"`
	ExpiresAt                    sql.NullString `json:"expires_at"`
}

func (q *Queries) CreateUserInputRequest(ctx context.Context, arg CreateUserInputRequestParams) (UserInputRequest, error) {
	row := q.db.QueryRowContext(ctx, createUserInputRequest,
		arg.BotID,
		arg.SessionID,
		arg.RouteID,
		arg.ChannelIdentityID,
		arg.ToolCallID,
		arg.ToolName,
		arg.InputJson,
		arg.UiPayloadJson,
		arg.ProviderMetadata,
		arg.RequestedByChannelIdentityID,
		arg.SourcePlatform,
		arg.ReplyTarget,
		arg.ConversationType,
		arg.ExpiresAt,
	)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failUserInputRequest = `-- name: FailUserInputRequest :one
UPDATE user_input_requests
SET status = 'failed',
    result_json = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at = '' OR julianday(expires_at) > julianday('now'))
RETURNING id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
`

type FailUserInputRequestParams struct {
	ResultJson string `json:"result_json"`
	ID         string `json:"id"`
}

func (q *Queries) FailUserInputRequest(ctx context.Context, arg FailUserInputRequestParams) (UserInputRequest, error) {
	row := q.db.QueryRowContext(ctx, failUserInputRequest, arg.ResultJson, arg.ID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPendingUserInputBySession = `-- name: GetLatestPendingUserInputBySession :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
FROM user_input_requests
WHERE bot_id = ?
  AND session_id = ?
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at = '' OR julianday(expires_at) > julianday('now'))
ORDER BY created_at DESC, short_id DESC
LIMIT 1
`

type GetLatestPendingUserInputBySessionParams struct {
	BotID     string `json:"bot_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetLatestPendingUserInputBySession(ctx context.Context, arg GetLatestPendingUserInputBySessionParams) (UserInputRequest, error) {
	row := q.db.QueryRowContext(ctx, getLatestPendingUserInputBySession, arg.BotID, arg.SessionID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingUserInputByReplyMessage = `-- name: GetPendingUserInputByReplyMessage :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
FROM user_input_requests
WHERE bot_id = ?
  AND session_id = ?
  AND prompt_external_message_id = ?
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at = '' OR julianday(expires_at) > julianday('now'))
ORDER BY created_at DESC
LIMIT 1
`

type GetPendingUserInputByReplyMessageParams struct {
	BotID                   string `json:"bot_id"`
	SessionID               string `json:"session_id"`
	PromptExternalMessageID string `json:"prompt_external_message_id"`
}

func (q *Queries) GetPendingUserInputByReplyMessage(ctx context.Context, arg GetPendingUserInputByReplyMessageParams) (UserInputRequest, error) {
	row := q.db.QueryRowContext(ctx, getPendingUserInputByReplyMessage, arg.BotID, arg.SessionID, arg.PromptExternalMessageID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingUserInputBySessionShortID = `-- name: GetPendingUserInputBySessionShortID :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
FROM user_input_requests
WHERE bot_id = ?
  AND session_id = ?
  AND short_id = ?
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at = '' OR julianday(expires_at) > julianday('now'))
`

type GetPendingUserInputBySessionShortIDParams struct {
	BotID     string `json:"bot_id"`
	SessionID string `json:"session_id"`
	ShortID   int64  `json:"short_id"`
}

func (q *Queries) GetPendingUserInputBySessionShortID(ctx context.Context, arg GetPendingUserInputBySessionShortIDParams) (UserInputRequest, error) {
	row := q.db.QueryRowContext(ctx, getPendingUserInputBySessionShortID, arg.BotID, arg.SessionID, arg.ShortID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserInputRequest = `-- name: GetUserInputRequest :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
FROM user_input_requests
WHERE id = ?
`

func (q *Queries) GetUserInputRequest(ctx context.Context, id string) (UserInputRequest, error) {
	row := q.db.QueryRowContext(ctx, getUserInputRequest, id)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserInputRequestBySessionToolCall = `-- name: GetUserInputRequestBySessionToolCall :one
SELECT id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
FROM user_input_requests
WHERE session_id = ?
  AND tool_call_id = ?
`

type GetUserInputRequestBySessionToolCallParams struct {
	SessionID  string `json:"session_id"`
	ToolCallID string `json:"tool_call_id"`
}

func (q *Queries) GetUserInputRequestBySessionToolCall(ctx context.Context, arg GetUserInputRequestBySessionToolCallParams) (UserInputRequest, error) {
	row := q.db.QueryRowContext(ctx, getUserInputRequestBySessionToolCall, arg.SessionID, arg.ToolCallID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingUserInputsBySession = `-- name: ListPendingUserInputsBySession :many
SELECT id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
FROM user_input_requests
WHERE bot_id = ?
  AND session_id = ?
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at = '' OR julianday(expires_at) > julianday('now'))
ORDER BY created_at ASC, short_id ASC
`

type ListPendingUserInputsBySessionParams struct {
	BotID     string `json:"bot_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) ListPendingUserInputsBySession(ctx context.Context, arg ListPendingUserInputsBySessionParams) ([]UserInputRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPendingUserInputsBySession, arg.BotID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInputRequest
	for rows.Next() {
		var i UserInputRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.ToolCallID,
			&i.ToolName,
			&i.ShortID,
			&i.Status,
			&i.InputJson,
			&i.UiPayloadJson,
			&i.ResultJson,
			&i.ProviderMetadata,
			&i.RequestedByChannelIdentityID,
			&i.RespondedByChannelIdentityID,
			&i.AssistantMessageID,
			&i.ToolResultMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.CanceledAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserInputsBySession = `-- name: ListUserInputsBySession :many
SELECT id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
FROM user_input_requests
WHERE bot_id = ?
  AND session_id = ?
ORDER BY created_at ASC, short_id ASC
`

type ListUserInputsBySessionParams struct {
	BotID     string `json:"bot_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) ListUserInputsBySession(ctx context.Context, arg ListUserInputsBySessionParams) ([]UserInputRequest, error) {
	rows, err := q.db.QueryContext(ctx, listUserInputsBySession, arg.BotID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInputRequest
	for rows.Next() {
		var i UserInputRequest
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.SessionID,
			&i.RouteID,
			&i.ChannelIdentityID,
			&i.ToolCallID,
			&i.ToolName,
			&i.ShortID,
			&i.Status,
			&i.InputJson,
			&i.UiPayloadJson,
			&i.ResultJson,
			&i.ProviderMetadata,
			&i.RequestedByChannelIdentityID,
			&i.RespondedByChannelIdentityID,
			&i.AssistantMessageID,
			&i.ToolResultMessageID,
			&i.PromptMessageID,
			&i.PromptExternalMessageID,
			&i.SourcePlatform,
			&i.ReplyTarget,
			&i.ConversationType,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.CanceledAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitUserInputRequest = `-- name: SubmitUserInputRequest :one
UPDATE user_input_requests
SET status = 'submitted',
    result_json = ?1,
    responded_by_channel_identity_id = ?2,
    responded_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?3
  AND status = 'pending'
  AND (expires_at IS NULL OR expires_at = '' OR julianday(expires_at) > julianday('now'))
RETURNING id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
`

type SubmitUserInputRequestParams struct {
	ResultJson                   string         `json:"result_json"`
	RespondedByChannelIdentityID sql.NullString `json:"responded_by_channel_identity_id"`
	ID                           string         `json:"id"`
}

func (q *Queries) SubmitUserInputRequest(ctx context.Context, arg SubmitUserInputRequestParams) (UserInputRequest, error) {
	row := q.db.QueryRowContext(ctx, submitUserInputRequest, arg.ResultJson, arg.RespondedByChannelIdentityID, arg.ID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserInputAssistantMessage = `-- name: UpdateUserInputAssistantMessage :one
UPDATE user_input_requests
SET assistant_message_id = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
RETURNING id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
`

type UpdateUserInputAssistantMessageParams struct {
	AssistantMessageID sql.NullString `json:"assistant_message_id"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdateUserInputAssistantMessage(ctx context.Context, arg UpdateUserInputAssistantMessageParams) (UserInputRequest, error) {
	row := q.db.QueryRowContext(ctx, updateUserInputAssistantMessage, arg.AssistantMessageID, arg.ID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserInputPromptMessage = `-- name: UpdateUserInputPromptMessage :one
UPDATE user_input_requests
SET prompt_message_id = ?1,
    prompt_external_message_id = ?2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?3
RETURNING id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
`

type UpdateUserInputPromptMessageParams struct {
	PromptMessageID         sql.NullString `json:"prompt_message_id"`
	PromptExternalMessageID string         `json:"prompt_external_message_id"`
	ID                      string         `json:"id"`
}

func (q *Queries) UpdateUserInputPromptMessage(ctx context.Context, arg UpdateUserInputPromptMessageParams) (UserInputRequest, error) {
	row := q.db.QueryRowContext(ctx, updateUserInputPromptMessage, arg.PromptMessageID, arg.PromptExternalMessageID, arg.ID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserInputToolResultMessage = `-- name: UpdateUserInputToolResultMessage :one
UPDATE user_input_requests
SET tool_result_message_id = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
RETURNING id, bot_id, session_id, route_id, channel_identity_id, tool_call_id, tool_name, short_id, status, input_json, ui_payload_json, result_json, provider_metadata, requested_by_channel_identity_id, responded_by_channel_identity_id, assistant_message_id, tool_result_message_id, prompt_message_id, prompt_external_message_id, source_platform, reply_target, conversation_type, expires_at, created_at, responded_at, canceled_at, updated_at
`

type UpdateUserInputToolResultMessageParams struct {
	ToolResultMessageID sql.NullString `json:"tool_result_message_id"`
	ID                  string         `json:"id"`
}

func (q *Queries) UpdateUserInputToolResultMessage(ctx context.Context, arg UpdateUserInputToolResultMessageParams) (UserInputRequest, error) {
	row := q.db.QueryRowContext(ctx, updateUserInputToolResultMessage, arg.ToolResultMessageID, arg.ID)
	var i UserInputRequest
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.SessionID,
		&i.RouteID,
		&i.ChannelIdentityID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ShortID,
		&i.Status,
		&i.InputJson,
		&i.UiPayloadJson,
		&i.ResultJson,
		&i.ProviderMetadata,
		&i.RequestedByChannelIdentityID,
		&i.RespondedByChannelIdentityID,
		&i.AssistantMessageID,
		&i.ToolResultMessageID,
		&i.PromptMessageID,
		&i.PromptExternalMessageID,
		&i.SourcePlatform,
		&i.ReplyTarget,
		&i.ConversationType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.CanceledAt,
		&i.UpdatedAt,
	)
	return i, err
}
