// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: acl.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBotACLRule = `-- name: CreateBotACLRule :one
INSERT INTO bot_acl_rules (
  bot_id,
  enabled,
  description,
  action,
  effect,
  channel_identity_id,
  subject_channel_type,
  source_channel,
  source_conversation_type,
  source_conversation_id,
  source_thread_id,
  created_by_user_id
)
VALUES (
  $1,
  $2,
  $5::text,
  'chat.trigger',
  $3,
  $6::uuid,
  $7::text,
  $8::text,
  $9::text,
  $10::text,
  $11::text,
  $4
)
RETURNING id, bot_id, action, effect, channel_identity_id, source_channel, source_conversation_type, source_conversation_id, source_thread_id, created_by_user_id, created_at, updated_at, enabled, description, subject_channel_type
`

type CreateBotACLRuleParams struct {
	BotID                  pgtype.UUID `json:"bot_id"`
	Enabled                bool        `json:"enabled"`
	Effect                 string      `json:"effect"`
	CreatedByUserID        pgtype.UUID `json:"created_by_user_id"`
	Description            pgtype.Text `json:"description"`
	ChannelIdentityID      pgtype.UUID `json:"channel_identity_id"`
	SubjectChannelType     pgtype.Text `json:"subject_channel_type"`
	SourceChannel          pgtype.Text `json:"source_channel"`
	SourceConversationType pgtype.Text `json:"source_conversation_type"`
	SourceConversationID   pgtype.Text `json:"source_conversation_id"`
	SourceThreadID         pgtype.Text `json:"source_thread_id"`
}

func (q *Queries) CreateBotACLRule(ctx context.Context, arg CreateBotACLRuleParams) (BotAclRule, error) {
	row := q.db.QueryRow(ctx, createBotACLRule,
		arg.BotID,
		arg.Enabled,
		arg.Effect,
		arg.CreatedByUserID,
		arg.Description,
		arg.ChannelIdentityID,
		arg.SubjectChannelType,
		arg.SourceChannel,
		arg.SourceConversationType,
		arg.SourceConversationID,
		arg.SourceThreadID,
	)
	var i BotAclRule
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Action,
		&i.Effect,
		&i.ChannelIdentityID,
		&i.SourceChannel,
		&i.SourceConversationType,
		&i.SourceConversationID,
		&i.SourceThreadID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.Description,
		&i.SubjectChannelType,
	)
	return i, err
}

const deleteBotACLRuleByID = `-- name: DeleteBotACLRuleByID :exec
DELETE FROM bot_acl_rules WHERE id = $1
`

func (q *Queries) DeleteBotACLRuleByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBotACLRuleByID, id)
	return err
}

const evaluateBotACLRule = `-- name: EvaluateBotACLRule :one
SELECT COALESCE((
  SELECT r.effect
  FROM bot_acl_rules r
  WHERE r.bot_id = b.id
    AND r.enabled = true
    AND r.action = $1
    AND r.effect <> b.acl_default_effect
    AND (r.subject_channel_type IS NULL OR r.subject_channel_type = $2::text)
    AND (r.channel_identity_id IS NULL OR r.channel_identity_id = $3::uuid)
    AND (r.source_conversation_type IS NULL OR r.source_conversation_type = $4::text)
    AND (r.source_conversation_id IS NULL OR r.source_conversation_id = $5::text)
    AND (r.source_thread_id IS NULL OR r.source_thread_id = $6::text)
  LIMIT 1
), b.acl_default_effect) AS effect
FROM bots b
WHERE b.id = $7
`

type EvaluateBotACLRuleParams struct {
	Action                 string      `json:"action"`
	SubjectChannelType     pgtype.Text `json:"subject_channel_type"`
	ChannelIdentityID      pgtype.UUID `json:"channel_identity_id"`
	SourceConversationType pgtype.Text `json:"source_conversation_type"`
	SourceConversationID   pgtype.Text `json:"source_conversation_id"`
	SourceThreadID         pgtype.Text `json:"source_thread_id"`
	BotID                  pgtype.UUID `json:"bot_id"`
}

// Mode-based ACL: only rules opposite to bots.acl_default_effect can override the default.
// If no matching override exists, returns bots.acl_default_effect.
func (q *Queries) EvaluateBotACLRule(ctx context.Context, arg EvaluateBotACLRuleParams) (string, error) {
	row := q.db.QueryRow(ctx, evaluateBotACLRule,
		arg.Action,
		arg.SubjectChannelType,
		arg.ChannelIdentityID,
		arg.SourceConversationType,
		arg.SourceConversationID,
		arg.SourceThreadID,
		arg.BotID,
	)
	var effect string
	err := row.Scan(&effect)
	return effect, err
}

const getBotACLDefaultEffect = `-- name: GetBotACLDefaultEffect :one
SELECT acl_default_effect FROM bots WHERE id = $1
`

func (q *Queries) GetBotACLDefaultEffect(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getBotACLDefaultEffect, id)
	var acl_default_effect string
	err := row.Scan(&acl_default_effect)
	return acl_default_effect, err
}

const listBotACLRules = `-- name: ListBotACLRules :many
SELECT
  r.id,
  r.bot_id,
  r.enabled,
  r.description,
  r.action,
  r.effect,
  r.channel_identity_id,
  r.subject_channel_type,
  r.source_conversation_type,
  r.source_conversation_id,
  r.source_thread_id,
  r.created_by_user_id,
  r.created_at,
  r.updated_at,
  ci.channel_type,
  ci.channel_subject_id,
  ci.display_name AS channel_identity_display_name,
  ci.avatar_url AS channel_identity_avatar_url,
  COALESCE(
    NULLIF(TRIM(COALESCE(source_route.metadata->>'conversation_name', '')), ''),
    NULLIF(TRIM(COALESCE(source_route.metadata->>'conversation_handle', '')), ''),
    ''
  )::text AS source_conversation_name,
  COALESCE(NULLIF(TRIM(COALESCE(source_route.metadata->>'conversation_avatar_url', '')), ''), '')::text AS source_conversation_avatar_url
FROM bot_acl_rules r
LEFT JOIN channel_identities ci ON ci.id = r.channel_identity_id
LEFT JOIN bot_channel_routes source_route ON source_route.bot_id = r.bot_id
  AND r.source_conversation_id IS NOT NULL
  AND source_route.external_conversation_id = r.source_conversation_id
  AND COALESCE(source_route.external_thread_id, '') = COALESCE(r.source_thread_id, '')
  AND (r.source_channel IS NULL OR source_route.channel_type = r.source_channel)
WHERE r.bot_id = $1
  AND r.action = 'chat.trigger'
ORDER BY r.created_at DESC
`

type ListBotACLRulesRow struct {
	ID                          pgtype.UUID        `json:"id"`
	BotID                       pgtype.UUID        `json:"bot_id"`
	Enabled                     bool               `json:"enabled"`
	Description                 pgtype.Text        `json:"description"`
	Action                      string             `json:"action"`
	Effect                      string             `json:"effect"`
	ChannelIdentityID           pgtype.UUID        `json:"channel_identity_id"`
	SubjectChannelType          pgtype.Text        `json:"subject_channel_type"`
	SourceConversationType      pgtype.Text        `json:"source_conversation_type"`
	SourceConversationID        pgtype.Text        `json:"source_conversation_id"`
	SourceThreadID              pgtype.Text        `json:"source_thread_id"`
	CreatedByUserID             pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	ChannelType                 pgtype.Text        `json:"channel_type"`
	ChannelSubjectID            pgtype.Text        `json:"channel_subject_id"`
	ChannelIdentityDisplayName  pgtype.Text        `json:"channel_identity_display_name"`
	ChannelIdentityAvatarUrl    pgtype.Text        `json:"channel_identity_avatar_url"`
	SourceConversationName      string             `json:"source_conversation_name"`
	SourceConversationAvatarUrl string             `json:"source_conversation_avatar_url"`
}

func (q *Queries) ListBotACLRules(ctx context.Context, botID pgtype.UUID) ([]ListBotACLRulesRow, error) {
	rows, err := q.db.Query(ctx, listBotACLRules, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBotACLRulesRow
	for rows.Next() {
		var i ListBotACLRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Enabled,
			&i.Description,
			&i.Action,
			&i.Effect,
			&i.ChannelIdentityID,
			&i.SubjectChannelType,
			&i.SourceConversationType,
			&i.SourceConversationID,
			&i.SourceThreadID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelType,
			&i.ChannelSubjectID,
			&i.ChannelIdentityDisplayName,
			&i.ChannelIdentityAvatarUrl,
			&i.SourceConversationName,
			&i.SourceConversationAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBotACLDefaultEffect = `-- name: SetBotACLDefaultEffect :exec
UPDATE bots SET acl_default_effect = $2, updated_at = now() WHERE id = $1
`

type SetBotACLDefaultEffectParams struct {
	ID               pgtype.UUID `json:"id"`
	AclDefaultEffect string      `json:"acl_default_effect"`
}

func (q *Queries) SetBotACLDefaultEffect(ctx context.Context, arg SetBotACLDefaultEffectParams) error {
	_, err := q.db.Exec(ctx, setBotACLDefaultEffect, arg.ID, arg.AclDefaultEffect)
	return err
}

const updateBotACLRule = `-- name: UpdateBotACLRule :one
UPDATE bot_acl_rules
SET
  enabled = $2,
  description = $4::text,
  effect = $3,
  channel_identity_id = $5::uuid,
  subject_channel_type = $6::text,
  source_channel = $7::text,
  source_conversation_type = $8::text,
  source_conversation_id = $9::text,
  source_thread_id = $10::text,
  updated_at = now()
WHERE id = $1
RETURNING id, bot_id, action, effect, channel_identity_id, source_channel, source_conversation_type, source_conversation_id, source_thread_id, created_by_user_id, created_at, updated_at, enabled, description, subject_channel_type
`

type UpdateBotACLRuleParams struct {
	ID                     pgtype.UUID `json:"id"`
	Enabled                bool        `json:"enabled"`
	Effect                 string      `json:"effect"`
	Description            pgtype.Text `json:"description"`
	ChannelIdentityID      pgtype.UUID `json:"channel_identity_id"`
	SubjectChannelType     pgtype.Text `json:"subject_channel_type"`
	SourceChannel          pgtype.Text `json:"source_channel"`
	SourceConversationType pgtype.Text `json:"source_conversation_type"`
	SourceConversationID   pgtype.Text `json:"source_conversation_id"`
	SourceThreadID         pgtype.Text `json:"source_thread_id"`
}

func (q *Queries) UpdateBotACLRule(ctx context.Context, arg UpdateBotACLRuleParams) (BotAclRule, error) {
	row := q.db.QueryRow(ctx, updateBotACLRule,
		arg.ID,
		arg.Enabled,
		arg.Effect,
		arg.Description,
		arg.ChannelIdentityID,
		arg.SubjectChannelType,
		arg.SourceChannel,
		arg.SourceConversationType,
		arg.SourceConversationID,
		arg.SourceThreadID,
	)
	var i BotAclRule
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Action,
		&i.Effect,
		&i.ChannelIdentityID,
		&i.SourceChannel,
		&i.SourceConversationType,
		&i.SourceConversationID,
		&i.SourceThreadID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Enabled,
		&i.Description,
		&i.SubjectChannelType,
	)
	return i, err
}
