// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bot_channel_admins.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBotChannelAdmin = `-- name: DeleteBotChannelAdmin :exec
DELETE FROM bot_channel_admins
WHERE bot_id = $1 AND channel_identity_id = $2
`

type DeleteBotChannelAdminParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	ChannelIdentityID pgtype.UUID `json:"channel_identity_id"`
}

func (q *Queries) DeleteBotChannelAdmin(ctx context.Context, arg DeleteBotChannelAdminParams) error {
	_, err := q.db.Exec(ctx, deleteBotChannelAdmin, arg.BotID, arg.ChannelIdentityID)
	return err
}

const getBotChannelAdmin = `-- name: GetBotChannelAdmin :one
SELECT id, bot_id, channel_identity_id, granted, created_by_user_id, created_at, updated_at
FROM bot_channel_admins
WHERE bot_id = $1 AND channel_identity_id = $2
`

type GetBotChannelAdminParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	ChannelIdentityID pgtype.UUID `json:"channel_identity_id"`
}

func (q *Queries) GetBotChannelAdmin(ctx context.Context, arg GetBotChannelAdminParams) (BotChannelAdmin, error) {
	row := q.db.QueryRow(ctx, getBotChannelAdmin, arg.BotID, arg.ChannelIdentityID)
	var i BotChannelAdmin
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.ChannelIdentityID,
		&i.Granted,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBotChannelAdmins = `-- name: ListBotChannelAdmins :many
SELECT
  a.id,
  a.bot_id,
  a.channel_identity_id,
  a.granted,
  a.created_by_user_id,
  a.created_at,
  a.updated_at,
  ci.channel_type,
  ci.channel_subject_id,
  ci.display_name AS channel_identity_display_name,
  ci.avatar_url AS channel_identity_avatar_url
FROM bot_channel_admins a
LEFT JOIN channel_identities ci ON ci.id = a.channel_identity_id
WHERE a.bot_id = $1
ORDER BY a.created_at DESC
`

type ListBotChannelAdminsRow struct {
	ID                         pgtype.UUID        `json:"id"`
	BotID                      pgtype.UUID        `json:"bot_id"`
	ChannelIdentityID          pgtype.UUID        `json:"channel_identity_id"`
	Granted                    bool               `json:"granted"`
	CreatedByUserID            pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	ChannelType                pgtype.Text        `json:"channel_type"`
	ChannelSubjectID           pgtype.Text        `json:"channel_subject_id"`
	ChannelIdentityDisplayName pgtype.Text        `json:"channel_identity_display_name"`
	ChannelIdentityAvatarUrl   pgtype.Text        `json:"channel_identity_avatar_url"`
}

func (q *Queries) ListBotChannelAdmins(ctx context.Context, botID pgtype.UUID) ([]ListBotChannelAdminsRow, error) {
	rows, err := q.db.Query(ctx, listBotChannelAdmins, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBotChannelAdminsRow
	for rows.Next() {
		var i ListBotChannelAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.ChannelIdentityID,
			&i.Granted,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelType,
			&i.ChannelSubjectID,
			&i.ChannelIdentityDisplayName,
			&i.ChannelIdentityAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBotChannelAdmin = `-- name: UpsertBotChannelAdmin :one
INSERT INTO bot_channel_admins (
  bot_id,
  channel_identity_id,
  granted,
  created_by_user_id
)
VALUES (
  $1,
  $2,
  $3,
  $4::uuid
)
ON CONFLICT (bot_id, channel_identity_id) DO UPDATE
  SET granted = EXCLUDED.granted,
      updated_at = now()
RETURNING id, bot_id, channel_identity_id, granted, created_by_user_id, created_at, updated_at
`

type UpsertBotChannelAdminParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	ChannelIdentityID pgtype.UUID `json:"channel_identity_id"`
	Granted           bool        `json:"granted"`
	CreatedByUserID   pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) UpsertBotChannelAdmin(ctx context.Context, arg UpsertBotChannelAdminParams) (BotChannelAdmin, error) {
	row := q.db.QueryRow(ctx, upsertBotChannelAdmin,
		arg.BotID,
		arg.ChannelIdentityID,
		arg.Granted,
		arg.CreatedByUserID,
	)
	var i BotChannelAdmin
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.ChannelIdentityID,
		&i.Granted,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
