// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel_identity_bindings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannelLinkCode = `-- name: CreateChannelLinkCode :one
INSERT INTO channel_link_codes (token, user_id, channel_type, expires_at)
VALUES ($1, $2, $4::text, $3)
RETURNING token, user_id, channel_type, expires_at, consumed_at, consumed_channel_identity_id, created_at
`

type CreateChannelLinkCodeParams struct {
	Token       string             `json:"token"`
	UserID      pgtype.UUID        `json:"user_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ChannelType pgtype.Text        `json:"channel_type"`
}

func (q *Queries) CreateChannelLinkCode(ctx context.Context, arg CreateChannelLinkCodeParams) (ChannelLinkCode, error) {
	row := q.db.QueryRow(ctx, createChannelLinkCode,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
		arg.ChannelType,
	)
	var i ChannelLinkCode
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ChannelType,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedChannelIdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserChannelIdentityBinding = `-- name: DeleteUserChannelIdentityBinding :exec
DELETE FROM user_channel_identity_bindings
WHERE user_id = $1 AND channel_identity_id = $2
`

type DeleteUserChannelIdentityBindingParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	ChannelIdentityID pgtype.UUID `json:"channel_identity_id"`
}

func (q *Queries) DeleteUserChannelIdentityBinding(ctx context.Context, arg DeleteUserChannelIdentityBindingParams) error {
	_, err := q.db.Exec(ctx, deleteUserChannelIdentityBinding, arg.UserID, arg.ChannelIdentityID)
	return err
}

const getChannelLinkCodeByToken = `-- name: GetChannelLinkCodeByToken :one
SELECT token, user_id, channel_type, expires_at, consumed_at, consumed_channel_identity_id, created_at
FROM channel_link_codes
WHERE token = $1
`

func (q *Queries) GetChannelLinkCodeByToken(ctx context.Context, token string) (ChannelLinkCode, error) {
	row := q.db.QueryRow(ctx, getChannelLinkCodeByToken, token)
	var i ChannelLinkCode
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ChannelType,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedChannelIdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const listChannelIdentityBindings = `-- name: ListChannelIdentityBindings :many
SELECT
  b.id,
  b.user_id,
  b.channel_identity_id,
  b.created_at,
  b.updated_at,
  ci.channel_type,
  ci.channel_subject_id,
  ci.display_name AS channel_identity_display_name,
  ci.avatar_url AS channel_identity_avatar_url
FROM user_channel_identity_bindings b
LEFT JOIN channel_identities ci ON ci.id = b.channel_identity_id
ORDER BY b.created_at DESC
`

type ListChannelIdentityBindingsRow struct {
	ID                         pgtype.UUID        `json:"id"`
	UserID                     pgtype.UUID        `json:"user_id"`
	ChannelIdentityID          pgtype.UUID        `json:"channel_identity_id"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	ChannelType                pgtype.Text        `json:"channel_type"`
	ChannelSubjectID           pgtype.Text        `json:"channel_subject_id"`
	ChannelIdentityDisplayName pgtype.Text        `json:"channel_identity_display_name"`
	ChannelIdentityAvatarUrl   pgtype.Text        `json:"channel_identity_avatar_url"`
}

func (q *Queries) ListChannelIdentityBindings(ctx context.Context) ([]ListChannelIdentityBindingsRow, error) {
	rows, err := q.db.Query(ctx, listChannelIdentityBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelIdentityBindingsRow
	for rows.Next() {
		var i ListChannelIdentityBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelIdentityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelType,
			&i.ChannelSubjectID,
			&i.ChannelIdentityDisplayName,
			&i.ChannelIdentityAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelIdentityBindingsForBot = `-- name: ListChannelIdentityBindingsForBot :many
SELECT DISTINCT
  b.id,
  b.user_id,
  b.channel_identity_id,
  b.created_at,
  b.updated_at,
  ci.channel_type,
  ci.channel_subject_id,
  ci.display_name AS channel_identity_display_name,
  ci.avatar_url AS channel_identity_avatar_url
FROM user_channel_identity_bindings b
INNER JOIN bot_user_grants g ON g.user_id = b.user_id AND g.bot_id = $1 AND g.subject_type = 'user'
LEFT JOIN channel_identities ci ON ci.id = b.channel_identity_id
ORDER BY b.created_at DESC
`

type ListChannelIdentityBindingsForBotRow struct {
	ID                         pgtype.UUID        `json:"id"`
	UserID                     pgtype.UUID        `json:"user_id"`
	ChannelIdentityID          pgtype.UUID        `json:"channel_identity_id"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	ChannelType                pgtype.Text        `json:"channel_type"`
	ChannelSubjectID           pgtype.Text        `json:"channel_subject_id"`
	ChannelIdentityDisplayName pgtype.Text        `json:"channel_identity_display_name"`
	ChannelIdentityAvatarUrl   pgtype.Text        `json:"channel_identity_avatar_url"`
}

func (q *Queries) ListChannelIdentityBindingsForBot(ctx context.Context, botID pgtype.UUID) ([]ListChannelIdentityBindingsForBotRow, error) {
	rows, err := q.db.Query(ctx, listChannelIdentityBindingsForBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelIdentityBindingsForBotRow
	for rows.Next() {
		var i ListChannelIdentityBindingsForBotRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelIdentityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelType,
			&i.ChannelSubjectID,
			&i.ChannelIdentityDisplayName,
			&i.ChannelIdentityAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelIdentityBindingsForUser = `-- name: ListChannelIdentityBindingsForUser :many
SELECT
  b.id,
  b.user_id,
  b.channel_identity_id,
  b.created_at,
  b.updated_at,
  ci.channel_type,
  ci.channel_subject_id,
  ci.display_name AS channel_identity_display_name,
  ci.avatar_url AS channel_identity_avatar_url
FROM user_channel_identity_bindings b
LEFT JOIN channel_identities ci ON ci.id = b.channel_identity_id
WHERE b.user_id = $1
ORDER BY b.created_at DESC
`

type ListChannelIdentityBindingsForUserRow struct {
	ID                         pgtype.UUID        `json:"id"`
	UserID                     pgtype.UUID        `json:"user_id"`
	ChannelIdentityID          pgtype.UUID        `json:"channel_identity_id"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	ChannelType                pgtype.Text        `json:"channel_type"`
	ChannelSubjectID           pgtype.Text        `json:"channel_subject_id"`
	ChannelIdentityDisplayName pgtype.Text        `json:"channel_identity_display_name"`
	ChannelIdentityAvatarUrl   pgtype.Text        `json:"channel_identity_avatar_url"`
}

func (q *Queries) ListChannelIdentityBindingsForUser(ctx context.Context, userID pgtype.UUID) ([]ListChannelIdentityBindingsForUserRow, error) {
	rows, err := q.db.Query(ctx, listChannelIdentityBindingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelIdentityBindingsForUserRow
	for rows.Next() {
		var i ListChannelIdentityBindingsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelIdentityID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelType,
			&i.ChannelSubjectID,
			&i.ChannelIdentityDisplayName,
			&i.ChannelIdentityAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDsByChannelIdentity = `-- name: ListUserIDsByChannelIdentity :many
SELECT user_id
FROM user_channel_identity_bindings
WHERE channel_identity_id = $1
`

func (q *Queries) ListUserIDsByChannelIdentity(ctx context.Context, channelIdentityID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUserIDsByChannelIdentity, channelIdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChannelLinkCodeConsumed = `-- name: MarkChannelLinkCodeConsumed :one
UPDATE channel_link_codes
SET consumed_at = now(),
    consumed_channel_identity_id = $2
WHERE token = $1 AND consumed_at IS NULL AND expires_at > now()
RETURNING token, user_id, channel_type, expires_at, consumed_at, consumed_channel_identity_id, created_at
`

type MarkChannelLinkCodeConsumedParams struct {
	Token                     string      `json:"token"`
	ConsumedChannelIdentityID pgtype.UUID `json:"consumed_channel_identity_id"`
}

func (q *Queries) MarkChannelLinkCodeConsumed(ctx context.Context, arg MarkChannelLinkCodeConsumedParams) (ChannelLinkCode, error) {
	row := q.db.QueryRow(ctx, markChannelLinkCodeConsumed, arg.Token, arg.ConsumedChannelIdentityID)
	var i ChannelLinkCode
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ChannelType,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedChannelIdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const redeemChannelLinkCode = `-- name: RedeemChannelLinkCode :one
WITH claimed AS (
  UPDATE channel_link_codes
  SET consumed_at = now(),
      consumed_channel_identity_id = $2
  WHERE token = $1
    AND consumed_at IS NULL
    AND expires_at > now()
  RETURNING user_id
)
INSERT INTO user_channel_identity_bindings (user_id, channel_identity_id)
SELECT user_id, $2
FROM claimed
ON CONFLICT (user_id, channel_identity_id) DO UPDATE
  SET updated_at = now()
RETURNING id, user_id, channel_identity_id, created_at, updated_at
`

type RedeemChannelLinkCodeParams struct {
	Token             string      `json:"token"`
	ChannelIdentityID pgtype.UUID `json:"channel_identity_id"`
}

func (q *Queries) RedeemChannelLinkCode(ctx context.Context, arg RedeemChannelLinkCodeParams) (UserChannelIdentityBinding, error) {
	row := q.db.QueryRow(ctx, redeemChannelLinkCode, arg.Token, arg.ChannelIdentityID)
	var i UserChannelIdentityBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelIdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserChannelIdentityBinding = `-- name: UpsertUserChannelIdentityBinding :one
INSERT INTO user_channel_identity_bindings (user_id, channel_identity_id)
VALUES ($1, $2)
ON CONFLICT (user_id, channel_identity_id) DO UPDATE
  SET updated_at = now()
RETURNING id, user_id, channel_identity_id, created_at, updated_at
`

type UpsertUserChannelIdentityBindingParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	ChannelIdentityID pgtype.UUID `json:"channel_identity_id"`
}

func (q *Queries) UpsertUserChannelIdentityBinding(ctx context.Context, arg UpsertUserChannelIdentityBindingParams) (UserChannelIdentityBinding, error) {
	row := q.db.QueryRow(ctx, upsertUserChannelIdentityBinding, arg.UserID, arg.ChannelIdentityID)
	var i UserChannelIdentityBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelIdentityID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
