// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"
)

const insertLifecycleEvent = `-- name: InsertLifecycleEvent :exec
INSERT INTO lifecycle_events (id, container_id, event_type, payload)
VALUES (
  $1,
  $2,
  $3,
  $4
)
`

type InsertLifecycleEventParams struct {
	ID          string `json:"id"`
	ContainerID string `json:"container_id"`
	EventType   string `json:"event_type"`
	Payload     []byte `json:"payload"`
}

func (q *Queries) InsertLifecycleEvent(ctx context.Context, arg InsertLifecycleEventParams) error {
	_, err := q.db.Exec(ctx, insertLifecycleEvent,
		arg.ID,
		arg.ContainerID,
		arg.EventType,
		arg.Payload,
	)
	return err
}
