// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fetch_providers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFetchProvider = `-- name: CreateFetchProvider :one
INSERT INTO fetch_providers (name, provider, config, enable)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, name, provider, config, enable, created_at, updated_at
`

type CreateFetchProviderParams struct {
	Name     string `json:"name"`
	Provider string `json:"provider"`
	Config   []byte `json:"config"`
	Enable   bool   `json:"enable"`
}

func (q *Queries) CreateFetchProvider(ctx context.Context, arg CreateFetchProviderParams) (FetchProvider, error) {
	row := q.db.QueryRow(ctx, createFetchProvider,
		arg.Name,
		arg.Provider,
		arg.Config,
		arg.Enable,
	)
	var i FetchProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.Enable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFetchProvider = `-- name: DeleteFetchProvider :exec
DELETE FROM fetch_providers WHERE id = $1
`

func (q *Queries) DeleteFetchProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFetchProvider, id)
	return err
}

const getFetchProviderByID = `-- name: GetFetchProviderByID :one
SELECT id, name, provider, config, enable, created_at, updated_at FROM fetch_providers WHERE id = $1
`

func (q *Queries) GetFetchProviderByID(ctx context.Context, id pgtype.UUID) (FetchProvider, error) {
	row := q.db.QueryRow(ctx, getFetchProviderByID, id)
	var i FetchProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.Enable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFetchProviderByName = `-- name: GetFetchProviderByName :one
SELECT id, name, provider, config, enable, created_at, updated_at FROM fetch_providers WHERE name = $1
`

func (q *Queries) GetFetchProviderByName(ctx context.Context, name string) (FetchProvider, error) {
	row := q.db.QueryRow(ctx, getFetchProviderByName, name)
	var i FetchProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.Enable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFetchProviders = `-- name: ListFetchProviders :many
SELECT id, name, provider, config, enable, created_at, updated_at FROM fetch_providers
ORDER BY created_at DESC
`

func (q *Queries) ListFetchProviders(ctx context.Context) ([]FetchProvider, error) {
	rows, err := q.db.Query(ctx, listFetchProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchProvider
	for rows.Next() {
		var i FetchProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Config,
			&i.Enable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFetchProvidersByProvider = `-- name: ListFetchProvidersByProvider :many
SELECT id, name, provider, config, enable, created_at, updated_at FROM fetch_providers
WHERE provider = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFetchProvidersByProvider(ctx context.Context, provider string) ([]FetchProvider, error) {
	rows, err := q.db.Query(ctx, listFetchProvidersByProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchProvider
	for rows.Next() {
		var i FetchProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Config,
			&i.Enable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFetchProvider = `-- name: UpdateFetchProvider :one
UPDATE fetch_providers
SET
  name = $1,
  provider = $2,
  config = $3,
  enable = $4,
  updated_at = now()
WHERE id = $5
RETURNING id, name, provider, config, enable, created_at, updated_at
`

type UpdateFetchProviderParams struct {
	Name     string      `json:"name"`
	Provider string      `json:"provider"`
	Config   []byte      `json:"config"`
	Enable   bool        `json:"enable"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateFetchProvider(ctx context.Context, arg UpdateFetchProviderParams) (FetchProvider, error) {
	row := q.db.QueryRow(ctx, updateFetchProvider,
		arg.Name,
		arg.Provider,
		arg.Config,
		arg.Enable,
		arg.ID,
	)
	var i FetchProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.Enable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
