// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMessageAssetsByBot = `-- name: CountMessageAssetsByBot :one
SELECT COUNT(*)
FROM bot_history_message_assets a
JOIN bot_history_messages m ON m.id = a.message_id
WHERE m.bot_id = $1
`

func (q *Queries) CountMessageAssetsByBot(ctx context.Context, botID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMessageAssetsByBot, botID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessageAsset = `-- name: CreateMessageAsset :one
INSERT INTO bot_history_message_assets (message_id, role, ordinal, content_hash, name, metadata)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
ON CONFLICT (message_id, content_hash) DO UPDATE SET
  role = EXCLUDED.role,
  ordinal = EXCLUDED.ordinal,
  name = EXCLUDED.name,
  metadata = EXCLUDED.metadata
RETURNING id, message_id, role, ordinal, content_hash, name, metadata, created_at
`

type CreateMessageAssetParams struct {
	MessageID   pgtype.UUID `json:"message_id"`
	Role        string      `json:"role"`
	Ordinal     int32       `json:"ordinal"`
	ContentHash string      `json:"content_hash"`
	Name        string      `json:"name"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateMessageAsset(ctx context.Context, arg CreateMessageAssetParams) (BotHistoryMessageAsset, error) {
	row := q.db.QueryRow(ctx, createMessageAsset,
		arg.MessageID,
		arg.Role,
		arg.Ordinal,
		arg.ContentHash,
		arg.Name,
		arg.Metadata,
	)
	var i BotHistoryMessageAsset
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Role,
		&i.Ordinal,
		&i.ContentHash,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createStorageProvider = `-- name: CreateStorageProvider :one
INSERT INTO storage_providers (name, provider, config)
VALUES ($1, $2, $3)
RETURNING id, name, provider, config, created_at, updated_at
`

type CreateStorageProviderParams struct {
	Name     string `json:"name"`
	Provider string `json:"provider"`
	Config   []byte `json:"config"`
}

func (q *Queries) CreateStorageProvider(ctx context.Context, arg CreateStorageProviderParams) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, createStorageProvider, arg.Name, arg.Provider, arg.Config)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMessageAssets = `-- name: DeleteMessageAssets :exec
DELETE FROM bot_history_message_assets WHERE message_id = $1
`

func (q *Queries) DeleteMessageAssets(ctx context.Context, messageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessageAssets, messageID)
	return err
}

const getBotStorageBinding = `-- name: GetBotStorageBinding :one
SELECT id, bot_id, storage_provider_id, base_path, created_at, updated_at FROM bot_storage_bindings WHERE bot_id = $1
`

func (q *Queries) GetBotStorageBinding(ctx context.Context, botID pgtype.UUID) (BotStorageBinding, error) {
	row := q.db.QueryRow(ctx, getBotStorageBinding, botID)
	var i BotStorageBinding
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.StorageProviderID,
		&i.BasePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorageProviderByID = `-- name: GetStorageProviderByID :one
SELECT id, name, provider, config, created_at, updated_at FROM storage_providers WHERE id = $1
`

func (q *Queries) GetStorageProviderByID(ctx context.Context, id pgtype.UUID) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, getStorageProviderByID, id)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorageProviderByName = `-- name: GetStorageProviderByName :one
SELECT id, name, provider, config, created_at, updated_at FROM storage_providers WHERE name = $1
`

func (q *Queries) GetStorageProviderByName(ctx context.Context, name string) (StorageProvider, error) {
	row := q.db.QueryRow(ctx, getStorageProviderByName, name)
	var i StorageProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessageAssets = `-- name: ListMessageAssets :many
SELECT id AS rel_id, message_id, role, ordinal, content_hash, name, metadata
FROM bot_history_message_assets
WHERE message_id = $1
ORDER BY ordinal ASC
`

type ListMessageAssetsRow struct {
	RelID       pgtype.UUID `json:"rel_id"`
	MessageID   pgtype.UUID `json:"message_id"`
	Role        string      `json:"role"`
	Ordinal     int32       `json:"ordinal"`
	ContentHash string      `json:"content_hash"`
	Name        string      `json:"name"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) ListMessageAssets(ctx context.Context, messageID pgtype.UUID) ([]ListMessageAssetsRow, error) {
	rows, err := q.db.Query(ctx, listMessageAssets, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessageAssetsRow
	for rows.Next() {
		var i ListMessageAssetsRow
		if err := rows.Scan(
			&i.RelID,
			&i.MessageID,
			&i.Role,
			&i.Ordinal,
			&i.ContentHash,
			&i.Name,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageAssetsBatch = `-- name: ListMessageAssetsBatch :many
SELECT id AS rel_id, message_id, role, ordinal, content_hash, name, metadata
FROM bot_history_message_assets
WHERE message_id = ANY($1::uuid[])
ORDER BY message_id, ordinal ASC
`

type ListMessageAssetsBatchRow struct {
	RelID       pgtype.UUID `json:"rel_id"`
	MessageID   pgtype.UUID `json:"message_id"`
	Role        string      `json:"role"`
	Ordinal     int32       `json:"ordinal"`
	ContentHash string      `json:"content_hash"`
	Name        string      `json:"name"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) ListMessageAssetsBatch(ctx context.Context, messageIds []pgtype.UUID) ([]ListMessageAssetsBatchRow, error) {
	rows, err := q.db.Query(ctx, listMessageAssetsBatch, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessageAssetsBatchRow
	for rows.Next() {
		var i ListMessageAssetsBatchRow
		if err := rows.Scan(
			&i.RelID,
			&i.MessageID,
			&i.Role,
			&i.Ordinal,
			&i.ContentHash,
			&i.Name,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageProviders = `-- name: ListStorageProviders :many
SELECT id, name, provider, config, created_at, updated_at FROM storage_providers ORDER BY created_at DESC
`

func (q *Queries) ListStorageProviders(ctx context.Context) ([]StorageProvider, error) {
	rows, err := q.db.Query(ctx, listStorageProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageProvider
	for rows.Next() {
		var i StorageProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBotStorageBinding = `-- name: UpsertBotStorageBinding :one
INSERT INTO bot_storage_bindings (bot_id, storage_provider_id, base_path)
VALUES ($1, $2, $3)
ON CONFLICT (bot_id) DO UPDATE SET
  storage_provider_id = EXCLUDED.storage_provider_id,
  base_path = EXCLUDED.base_path,
  updated_at = now()
RETURNING id, bot_id, storage_provider_id, base_path, created_at, updated_at
`

type UpsertBotStorageBindingParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	StorageProviderID pgtype.UUID `json:"storage_provider_id"`
	BasePath          string      `json:"base_path"`
}

func (q *Queries) UpsertBotStorageBinding(ctx context.Context, arg UpsertBotStorageBindingParams) (BotStorageBinding, error) {
	row := q.db.QueryRow(ctx, upsertBotStorageBinding, arg.BotID, arg.StorageProviderID, arg.BasePath)
	var i BotStorageBinding
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.StorageProviderID,
		&i.BasePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
