// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: network.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBotOverlayConfig = `-- name: GetBotOverlayConfig :one
SELECT
  overlay_enabled,
  overlay_provider,
  overlay_config
FROM bots
WHERE id = $1
`

type GetBotOverlayConfigRow struct {
	OverlayEnabled  bool   `json:"overlay_enabled"`
	OverlayProvider string `json:"overlay_provider"`
	OverlayConfig   []byte `json:"overlay_config"`
}

func (q *Queries) GetBotOverlayConfig(ctx context.Context, id pgtype.UUID) (GetBotOverlayConfigRow, error) {
	row := q.db.QueryRow(ctx, getBotOverlayConfig, id)
	var i GetBotOverlayConfigRow
	err := row.Scan(&i.OverlayEnabled, &i.OverlayProvider, &i.OverlayConfig)
	return i, err
}
