// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_resource_limits.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBotWorkspaceResourceLimits = `-- name: GetBotWorkspaceResourceLimits :one
SELECT bot_id, cpu_millicores, memory_bytes, storage_bytes, created_at, updated_at FROM bot_workspace_resource_limits WHERE bot_id = $1
`

func (q *Queries) GetBotWorkspaceResourceLimits(ctx context.Context, botID pgtype.UUID) (BotWorkspaceResourceLimit, error) {
	row := q.db.QueryRow(ctx, getBotWorkspaceResourceLimits, botID)
	var i BotWorkspaceResourceLimit
	err := row.Scan(
		&i.BotID,
		&i.CpuMillicores,
		&i.MemoryBytes,
		&i.StorageBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBotWorkspaceResourceLimits = `-- name: UpsertBotWorkspaceResourceLimits :one
INSERT INTO bot_workspace_resource_limits (
  bot_id, cpu_millicores, memory_bytes, storage_bytes
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
ON CONFLICT (bot_id) DO UPDATE SET
  cpu_millicores = EXCLUDED.cpu_millicores,
  memory_bytes = EXCLUDED.memory_bytes,
  storage_bytes = EXCLUDED.storage_bytes,
  updated_at = now()
RETURNING bot_id, cpu_millicores, memory_bytes, storage_bytes, created_at, updated_at
`

type UpsertBotWorkspaceResourceLimitsParams struct {
	BotID         pgtype.UUID `json:"bot_id"`
	CpuMillicores int64       `json:"cpu_millicores"`
	MemoryBytes   int64       `json:"memory_bytes"`
	StorageBytes  int64       `json:"storage_bytes"`
}

func (q *Queries) UpsertBotWorkspaceResourceLimits(ctx context.Context, arg UpsertBotWorkspaceResourceLimitsParams) (BotWorkspaceResourceLimit, error) {
	row := q.db.QueryRow(ctx, upsertBotWorkspaceResourceLimits,
		arg.BotID,
		arg.CpuMillicores,
		arg.MemoryBytes,
		arg.StorageBytes,
	)
	var i BotWorkspaceResourceLimit
	err := row.Scan(
		&i.BotID,
		&i.CpuMillicores,
		&i.MemoryBytes,
		&i.StorageBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
